webpack.config.js

See the related [issue and workaround](https://github.com/microsoft/vscode-extension-telemetry/issues/41#issuecomment-598852991)

Resolve warnings due to missing dependencies for App Insights

---

src/client/test/unit/BlockingQueue.test.ts
src/common/utilities/BlockingQueue.ts

Event generated items, such as output "returned" by a child process on its stdout stream can only be processed once we are off the thread, so we'll need to throw them into this blocking queue to wait for and resume after receiving the event.

Blocking Queue to permit consumption of async/event returned items

---

package.json
src/client/lib/PacTerminal.ts

[Task 2362548: PAC Help via Command Pallet](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2362548)
This adds various PAC Help commands to the command pallet, which will run those commands in the current active terminal or create a new one if no terminal exists.

Adding Help commands to Command Pallet

---

package.json
src/client/extension.ts

Disable the extension from running remotely / in Codespaces, as work to support such has not yet been done.
[AB#2373053](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2373053) Power Platform VS Code extension gets installed in codespaces even when it is not supported

Disable Remote/Codespaces installation

---

README.md
gulpfile.js

not really needed, but a preemptive update to avoid customer confusion why there's a 1.8.6 pac CLI nupkg, but not in VS Code
will cherry-pick this one to release/stable to refresh the latest .vsix in VS Marketplace

update to pac CLI 1.8.6

---

.eslintrc.js
package.json
src/client/lib/PacActivityBarUI.ts
src/client/lib/PacTerminal.ts
src/client/pac/PacTypes.ts
src/client/pac/PacWrapper.ts

Initial work on the Auth, Solution, and Admin Environments panels.
As this is still under flux and not ready for release yet, the panels are all behind a `powerplatform.experimental.activityBarPanels` "feature flag" implemented with the Configuration schema through the VS Code settings.
[AB#2335295](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2335295) : UI - initial Auth Profiles panel
[Task 2336580: UI - Add new Auth Profile button/command](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2336580)
[Task 2335322: UI - Admin Environments](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2335322)
[Task 2335311: UI - Solutions display](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2335311)

Initial Auth, Solution, and Admin Environments panels

---

src/client/lib/CliAcquisition.ts
tsconfig.json

[AB#2400076](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2400076) - Handle PAC process conflicts on upgrade / debug
When debugging the extension using a different version of PAC than the current one (as well as some extension upgrade scenarios), the debugger instance of VS Code may have the PAC assemblies in use and locked, preventing the debuggee instance of VS Code from overwriting them with the new version.

Handle in-use PAC processes for debugging / upgrade scenarios

---

src/client/lib/PanelComponents.ts

Truncate Dataverse auth profile description for better readability
Add tooltip which shows all the details for auth profile.
Example:
Tooltip for Dataverse auth profile would look like, DATAVERSE: {profileName} {orgUrl} {user}
Tooltip for Admin auth profile, ADMIN: {profileName} {user}
[Truncate Dataverse auth profile description and add tooltip](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2399914/)

truncate dataverse auth profile description and add tooltip

---

package.json
src/client/lib/PacActivityBarUI.ts
src/client/lib/PanelComponents.ts

Add context menus for auth, solution and environment panels.
Context menu for Auth Panel,
Dataverse auth profile: Navigate to Resource 
Both the auth profiles: Copy User
Context menu for Environment Panel,
Copy Display Name
Copy Environment Id
Copy Environment Url
Copy Organization Id
Context menu for Solution Panel,
Copy Friendly Name
Copy Version Number
[Work item: Context menu commands](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2396563/)

add context menus for auth, environment and solution panels

---

package.json

Add message for empty auth profiles panel and buttons to create Dataverse and Admin auth profiles.
[Work item: Add content for empty auth profiles panel](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2224160)

add empty auth profiles content

---

package.json

Most of the panel related commands are context specific (eg "Copy Environment Id" for Environments), and thus prevented from displaying in the Command Palette.  
Three however - new dataverse auth profile, new admin auth profile, and clear auth profiles - do not need that context, and as such can be used from the command palette.   
This change adds those three to our `Power Platform CLI` category

Categorize commands exposed to the Command Palette

---

README.md
gulpfile.js
package.json
src/client/test/unit/CliAcquisition.test.ts

- update to latest pac CLI 1.9.8
- update release notes
- extend timeout for slower CLI acquisition tests

Prepare for August refresh release

---

package-lock.json
package.json
src/server/test/unit/liquidTagGrammer.test.ts

webpack >= 5.61.0 has the fix/mitigation
see: https://github.com/webpack/webpack/issues/14532
Fix lint/compile error in liquidTagGrammer.test.ts that is now flagged
in webpack (and remove bad eslint suppressions)

Fix nodejs17 and webpack 5 error: digital envelope routines::unsupported

---

gulpfile.js

[AB#2527929](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2527929): VS Code localizations not loading on WSL
When built on Windows, `vscode-nls-dev/lib/webpack-loader` uses Windows styled paths in `extension.js` and `dist/src/client/lib/*.nls.metadata.json`, breaking the loading of localization messages on Linux & Mac.
Builds on the other environments work fine, but for Windows builds (such as the official release process), we need to do the string replacement to fix up those paths.

Fix webpacked localization for non-Windows environments

---

README.md
src/client/lib/PacTerminal.ts

Roll forward to .NET 6.0 for M1 mac users when 6.0 uninstalls the 5.0 runtime

Roll forward to .NET 6.0 for M1 mac users when 6.0 uninstalls the 5.0 runtime

---

loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.cs.json
package.nls.de.json
package.nls.es.json
package.nls.fr.json
package.nls.it.json
package.nls.ja.json
package.nls.json
package.nls.ko.json
package.nls.pt-BR.json
package.nls.ru.json
package.nls.tr.json
package.nls.zh-CN.json
package.nls.zh-TW.json
src/client/lib/PacActivityBarUI.ts

[AB#2553702](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2553702): Auth Panel Updates - Remove Admin profiles from display and commands
As all actions done by the UI layer will be using Dataverse auth profiles with Token Exchange occurring in the background, the Admin auth profiles are not needed and can cause confusion by their presence.

Remove unneeded Admin profiles from the Auth Profile panel

---

gulpfile.js
src/client/lib/PacActivityBarUI.ts
src/client/lib/PanelComponents.ts
src/client/pac/PacWrapper.ts

[AB#2569818](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2569818): Solution List optimization - use URL instead of ID
Switching the call to use the URL for `pac solution list -env [url]` prevents the need to call the Global Discovery Service to map the Environment ID to the URL necessary for the Dataverse connection

Env & Solution panel should use the URL version of `pac solution list`

---

package-lock.json
package.json

[AB#2590007](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2590007): VS Code fails to install on Win 11 insider rings - Update to `find-process` 1.4.7 for Win 11 deprecation of WMIC
Windows 11 insider builds have removed WMIC, which is used by the `find-process` v1.4.4 package as part of the upgrade/installation pathway.  Thus, installation of the VS Code extension fails on those insider builds.
The `find-process` package already [found and fixed this issue on v1.4.7](https://github.com/yibn2008/find-process/pull/52/files), thus updating here resolves the installation failure.

Fixing installation issue on Win 11 insider builds

---

README.md

Missing newline in the release notes causes MD to cause the lines to run together

Fixing formatting of release notes

---

README.md
gulpfile.js
loc/translations-export/vscode-powerplatform.xlf
package.nls.json

Update PAC and release notes for Feb release, and inform non-WSL remote users to use the `--deviceCode` auth flow when necessary
[AB#2588409](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2588409): Inform CodeSpaces/Remote users to use Device Code flow

Update PAC and release notes for Feb release

---

loc/translations-export/vscode-powerplatform.xlf
src/client/lib/PacActivityBarUI.ts

PAC side validation allows for 30 character max, though its error message also claims it to be 12 characters.  
Fix for that side in ADO side PR.
[AB#2724005](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2724005) and #198 -  AuthProfile name argument validation differs in PAC and VS Code

Update Auth Name validation to match PAC

---

src/client/pac/PacWrapper.ts

As reported in #215 (and similar to Issue #139 / PR #141), we have issues with running the currently net5.0 PAC on M1 macs when net6.0 has been installed on the machine.  This isn't an issue for PAC run in the terminal per the previous fix, but the `DOTNET_ROLL_FORWARD` environment variable was only set for the terminal PAC instances, and not the PAC process spawned for the UI backend.
This was missed in bugbash as the environment variable was set machine wide in our earlier tests that produced the #141 fix, and hadn't since been removed.

Apply DOTNET_ROLL_FORWARD to the PAC UI Backend for M1 Macs

---

src/web/client/common/authenticationProvider.ts
src/web/client/common/constants.ts
src/web/client/common/localStore.ts
src/web/client/common/portalSchema.ts
src/web/client/common/portalSchemaReader.ts
src/web/client/extension.ts

Power Pages vscode.dev web extension schema and local store added
Testing:
tested with portal route - http://localhost:3000/powerplatform/default/adx_webtemplates/97a5603a-3ab0-ec11-9840-000d3a5a4b78?orgUrl=orgca400f6b.crm.dynamics.com&source=dataverse&schema=portalDataverseoldschema

Power Pages vscode.dev web extension schema and local store added

---

.github/workflows/PullRequest.yml

Including Ubuntu builds, as the extension is now being used more frequently in CodeSpaces and WSL scenarios.
Disabling `fail-fast`, so that any issues specific to one OS are clearer, instead of stopping the other OSs' build and test loops early.

PR Build Updates - Include Ubuntu, and disable fail-fast

---

src/web/client/common/authenticationProvider.ts
src/web/client/common/constants.ts
src/web/client/common/portalSchemaInterface.ts
src/web/client/common/remoteFetchProvider.ts
src/web/client/common/remoteSaveProvider.ts

Added save entity detailed structure and enhancements
Testing:
tested with portal route - http://localhost:3000/powerplatform/portal/webpages/563a8e53-6cf7-ec11-82e4-000d3a8b4b81?orgUrl=org4e297bda.crm10.dynamics.com&source=dataverse&schema=portalDataverseoldschema&websiteId=24828659-6cf7-ec11-82e4-000d3a8b4b81

Remote Save Provider refactoring and enhancements 

---

src/web/client/common/authenticationProvider.ts
src/web/client/common/localStore.ts
src/web/client/common/portalSchemaInterface.ts
src/web/client/common/portalSchemaReader.ts
src/web/client/common/remoteFetchProvider.ts
src/web/client/extension.ts

Testing:
tested with portal route -
http://localhost:3000/powerplatform/portal/webpages/563a8e53-6cf7-ec11-82e4-000d3a8b4b81?orgUrl=https://org4e297bda.crm10.dynamics.com&dataSource=Dataverse&schema=portalDataverseoldschema&websiteId=24828659-6cf7-ec11-82e4-000d3a8b4b81&websiteName=Site%205&clientSessionId=20d30dc0-040a-11ed-a9c5-d5d08bd7e3e0&Client=PowerPagesStudio

Lint fixes for power pages web extension

---

webpack.config.js

Due to the current limitation of vscode.dev - localization of external string does not work in the web extension. 
More details here: https://github.com/microsoft/vscode/issues/82595
This feature is expected to be available in September 2022
Temporary fix is to avoid the web extension from breaking is to offload nls loader from webconfig
Requirements: https://github.com/microsoft/vscode-dev/issues/477
Testing:

Localization fix for web extension

---

package.json

Reason for this change is captured in the GitHub Issue: [228](https://github.com/microsoft/powerplatform-vscode/issues/228)
Though at the moment the extension gets activated on a variety of events...but if we remove other activation events the extension will be activated when:
Workspace contains a file/folder ending with .portalconfig at any level of depth.
Tested with this change (and removing other activation events):

removed on language activation events and switched to a more specific event

---

loc/translations-export/vscode-powerplatform.xlf
src/web/client/common/constants.ts
src/web/client/extension.ts
webpack.config.js

Added site visibility dialog
updated the image with new changes

Site visibility dialog

---

src/web/client/common/constants.ts
src/web/client/common/portalSchema.ts
src/web/client/common/portalSchemaInterface.ts
src/web/client/common/remoteFetchProvider.ts
src/web/client/common/remoteSaveProvider.ts
src/web/client/utility/CommonUtility.ts

We need to write mimetype for css files as they are base64 encoded and dataverse overwirtes mimetype in these cases. This will fix css load in portals runtime.

CSS mimetype update - studio runtime fix

---

src/web/client/common/constants.ts
src/web/client/common/remoteFetchProvider.ts
src/web/client/extension.ts

Contains changes to show walkthrough only for the first run experience

changes to show walkthrough only for the first run experience

---

.azure-pipelines/OfficialBuild.yml

Contributing.md mentions the Node 16.x requirement, but the official build was using 14.
16+ is required for the `npm pkg set` commands in the `packageVSIX` gulp task.
[AB#3010171](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3010171)

Use node 16.x in official builds, as our Contributing.md already requires

---

.azure-pipelines/OfficialBuild.yml

The latest build agent update in AzDevOps no longer contains .netcore2 which was the required runtime for ESRP@1
A recent ESRP v2 release added support for .net6
https://aka.ms/esrp.signtask
validated in rel/stable for 1.1.9
https://dev.azure.com/dynamicscrm/OneCRM/_build/results?buildId=10820039&view=results
cherry pick of commit bfdd9cd in rel/stable

update to ESRP@2 to fix build break due to missing .net runtime

---

src/client/extension.ts
src/client/power-pages/commonUtility.ts
src/client/power-pages/constants.ts
src/client/power-pages/fileSystemCallbacks.ts
src/client/power-pages/validationDiagnostics.ts

- Covered single and multifile delete scenario for desktop extension - including output to diagnostics window for name references
- Code is behind the Configuration setting for CRUD operations on desktop extension
TODO:
- Check localization once the new localization API related changes are in
- Telemetry will be added in a separate task

Web pages delete file scenario - single and multi file delete

---

src/client/lib/PacActivityBarUI.ts
src/client/lib/PanelComponents.ts

Set a FileWatch on the auth profiles to auto-refresh the Auth panel when changes are made via CLI
[AB#2336573](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2336573)

Auto-refresh Auth panel on changes made via CLI

---

.gitattributes
gulpfile.js
l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf

- ensure l10n only LF style endings for l10n files
- ensure generated l10n files use `\n` not `\r\n` literals
- commit exported strings missed by a previous PR

Minor LOC cleanup

---

README.md

Making the arm64 MacOS requirements of both the x64 and arm64 versions of the net6.0 sdk clearer
#503

Make the M1 Mac requirements simpler to find than lines in the release notes

---

src/web/client/WebExtensionContext.ts
src/web/client/dal/fileSystemProvider.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/services/etagHandlerService.ts
src/web/client/telemetry/constants.ts
src/web/client/utilities/commonUtil.ts
src/web/client/utilities/fileAndEntityUtil.ts
src/web/client/utilities/folderHelperUtility.ts

This addresses corner scenario where difference in etag of a recently saved entity triggers un-necessary diff view

diff view - handle etag update after save

---

src/web/client/dal/fileSystemProvider.ts
src/web/client/services/etagHandlerService.ts

handles corner case where a diff view shows up even when there has been no change in file's content. Etag value can be updated on any change  being made in the entity and is not restricted to file content updates

handle un-necessary Diff view render on  Entity Etag changes

---

src/web/client/WebExtensionContext.ts
src/web/client/common/authenticationProvider.ts
src/web/client/common/constants.ts
src/web/client/dal/fileSystemProvider.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/dal/remoteSaveProvider.ts
src/web/client/schema/portalSchema.ts
src/web/client/services/etagHandlerService.ts
src/web/client/test/integration/AuthenticationProvider.test.ts
src/web/client/test/integration/WebExtensionContext.test.ts
src/web/client/test/integration/urlBuilderUtil.test.ts
src/web/client/utilities/folderHelperUtility.ts
src/web/client/utilities/urlBuilderUtil.ts

Dataverse odata calls response with "@odata.nextLink" gives the option to fetch all associated entities for a large portal. Introducing this change here behind multi-file feature flag.

Introduce continuation token to fetch files for large sites

---

loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json

[AB#3380985](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3380985)
When installing the Extension on a web-only environment such as vscode.dev, our limitation warning shows the localization slug instead of the explaination text:
This warning is displayed by VS Code itself (not our extension), and thus our extension does not run and the string cannot be replaced with the localized version.   This will unfortunately need to just be a plain English text.

Fixing web limitation message

---

package-lock.json
package.json
src/web/client/WebExtensionContext.ts
src/web/client/common/constants.ts
src/web/client/context/fileData.ts
src/web/client/context/fileDataMap.ts
src/web/client/dal/fileSystemProvider.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/schema/portalSchema.ts
src/web/client/utilities/commonUtil.ts

Webfile support all files in old and new data model
File content can be lazy loaded for new data model as that is an explicit call to get content. For media files this content is marked for on-click load as this doesn't impact time-to-search.
NOTE: There is an issue in loading content of media files for preview that will be addressed in a separate PR.

Support loading all webfiles - old and new data model

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/pac/PacWrapper.ts
src/client/pac/PacWrapperContext.ts
src/client/test/unit/PacWrapper.test.ts

[AB#3491579](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3491579)
Previously, logging in against any cloud other than Public needed to be done on the command line, as seen in #544 
This change provides configuration options in the VS Code Settings to choose another cloud:

Setting to enable authentication against other Azure clouds

---

package-lock.json
package.json

`vsce` was renamed to `@vscode/vsce`.
This repo already includes and uses the renamed version of the package, but the old one was never removed.

Remove unused vsce package

---

src/web/client/context/fileData.ts
src/web/client/context/fileDataMap.ts
src/web/client/dal/fileSystemProvider.ts
src/web/client/services/etagHandlerService.ts
src/web/client/utilities/fileAndEntityUtil.ts

This change addresses the scenario when a Conflict resolution editor is opened for user to compare the code changes in Dataverse entity v/s local changes, and the user discards the local changes to accept incoming server changes. Subsequent diff view calls are now optimized since the entity Etag is updated to latest in this scenario as well.

Update Entity Etag in case-of server side changes chosen scenario

---

src/web/client/dal/remoteFetchProvider.ts

File names used to for files loaded in file explorer is already sanitized. But, for entities like webpages, and advanced forms - we do not sanitize the folder name currently - which is also based on Name parameter fetched from entity records. This is an optimization PR based on the exceptions monitoring.

Extending the name sanitization done on file names to folder names which are based on entity name values

---

src/web/client/dal/fileSystemProvider.ts
src/web/client/extension.ts

We have a race condition where while we pro-actively load a file open in editor from a previous session, the load entire power pages code path is not triggered, This happens as the load of already open file flow creates the root directory, and hence the readDirectory flow for first time data load is not hit as entry is already present.

Always trigger activation path load of folders - fix race condition on preemptive root directory creation

---

src/web/client/dal/remoteFetchProvider.ts
src/web/client/utilities/urlBuilderUtil.ts

CSS mime type was getting corrupted after edit from vscode web extension causing the CSS rendering on runtime to be off for a power pages site. This fix reads the mimetype correctly from backend and writes back the field during save of webfile content.

Mimetype regression fix for old data model webfiles save scenario

---

src/web/client/dal/remoteFetchProvider.ts
src/web/client/schema/portalSchema.ts

FOr old data model we can have multiple files attached to a single webfile instance. IN vscode web extension view - we will default to showing the latest modified file in the attched file list

In case of multiple annotations/attachments associated with a  webfile pick the latest modified by the user

---

src/web/client/common/constants.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/utilities/commonUtil.ts

Webfile attachements maintained in dataverse will now be pulled depending on the right schema version validation and for old data model attachements present validation as well. This fix address new data model load file regression introduced while fixing old data model multiple annotations scenario.

New data model load file content fix

---

README.md
src/web/client/common/constants.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/utilities/commonUtil.ts

Original PR cherry picked here: https://github.com/microsoft/powerplatform-vscode/pull/693

New data model load file content fix (#693)

---

src/common/copilot/PowerPagesCopilot.ts

We are currently showing unavailable message and the welcome banner in vscode web copilot - which can be confusing for the users. This was happening in web co-pilot due to async execution of webview event  causing the unavailable banner to be executing first compared to the welcome event tirggered from Copilot JS script.

Do not show welcome banner in non-us orgs

---

src/web/client/webViews/powerPagesNavigationProvider.ts

There is a bug in Vscode dev extension testing for css and svg path load in vscode currently which makes verifying this scenario tricky in development. 
https://github.com/microsoft/vscode-dev/issues/987
Updating the path to correctly fetch the svg file for action icon display now.

Action icon buttons code path correction

---

.azure-pipelines/OfficialBuild.yml

- `npm pkg get version` is returning a string containing quotes `"`, which ADO build versioning needs removed.
- typo in ADO parameter use `parameter` -> `parameters`
- re-enable release branch triggers for the official build

Official Build Fixes

---

src/web/client/WebExtensionContext.ts
src/web/client/common/errorHandler.ts
src/web/client/context/entityData.ts
src/web/client/context/entityDataMap.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/schema/constants.ts
src/web/client/schema/portalSchema.ts
src/web/client/services/etagHandlerService.ts
src/web/client/telemetry/constants.ts
src/web/client/utilities/commonUtil.ts

In this PR I'm trying to add rootpageId in the entity data

RootWebPageId in Entity Data Map for V1 and V2 data model

---

src/web/client/WebExtensionContext.ts
src/web/client/context/entityForeignKeyDataMap.ts
src/web/client/dal/remoteFetchProvider.ts
src/web/client/telemetry/constants.ts

created Entity Foreign Key Data Map
storing rootWebPageId as Key vs Set of content page id
Content Page Id is Entity Id in terms of vscode for web and a single root page id can correspond to multiple entity id if content is localized in multiple language

created entity foreign key data map

---

src/web/client/common/worker/webworker.js

Updating data to passed in user data map, adding Aad Object Id instead of user Id, because it can be further consumed to get mail and profile picture using Microsoft graph client.

passing aadObject Id in container in user data map instead of user id

---

src/web/client/common/interfaces.ts
src/web/client/common/worker/webworker.js
src/web/client/extension.ts

In this PR I'm writing back in fluid container from the web extension
I'm writing the rootWebPageId of the file user is present on against his current connection
resulting in showing his presence on studio on the same file
https://github.com/microsoft/powerplatform-vscode/assets/56073559/5a38ec61-4e32-4b9c-890e-e1d62115646c

Writing back in fluid container from web side

---

package-lock.json
package.json

Per the discussion on [this thread ](https://github.com/microsoft/vscode/issues/200895) the issue with integration test case run failure is due to failure to unbundle and launch vscode in integration test run process. Upgrading the test-electron version fixed the issue on local. Creating this PR to validate and fix this issue.

Integration test case failure fix: Bump up vscode/test-electron version per solution for vscode launch failure

---

gulpfile.mjs
src/common/OneDSLoggerTelemetry/oneDSLogger.ts
src/common/telemetry/collectorEndpointProd.ts
src/common/telemetry/collectorEndpointTip.ts

We need to send telemetry data to TIP or PROD region. Using officialBuild we decide the endpoint. Introduced another function setCollectorEndpoint which determines the collectorEndpointURL and the same is consumed in oneDSLogger.

Set collectorEndpoint URL at build time

---

gulpfile.mjs
src/common/OneDSLoggerTelemetry/oneDSLogger.ts
src/common/OneDSLoggerTelemetry/shortNameMappingToAzureRegion.ts
src/common/telemetry/buildRegionProd.ts
src/common/telemetry/buildRegionTip.ts
src/web/client/extension.ts
src/web/client/telemetry/webExtensionTelemetry.ts
src/web/client/test/integration/AuthenticationProvider.test.ts

Integrate OneDSLoggerWrapper in WebExtensionTelemetry
Introduce a constant shortNameMappingtoAzureRegion. It will later used in OneDSLogger.

Integrate OneDSLoggerWrapper in WebExtensionTelemetry

---

.github/CODEOWNERS

[Codeowners docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file)
Multiple owners can be listed per line, and the last line which matches the pattern takes precedence, so Ashish's line would never kick in.

Fixing codeowners

---

src/web/client/extension.ts
src/web/client/webViews/QuickPickProvider.ts

Refresh users in quickpick on "update connected users" or "remove connected users"

Refresh QuickPickProvider on user collaboration events

---

package.json
src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts
src/common/OneDSLoggerTelemetry/telemetryConstants.ts
src/common/Utils.ts

[https://code.visualstudio.com/api/extension-guides/telemetry](https://code.visualstudio.com/api/extension-guides/telemetry)
Based on users selection, telemetry will be logged.
By default, flag value is true.

Introducing Feature flag for telemetry in Power Pages

---

package-lock.json
package.json

This pull request includes changes to the `package.json` file to specify the minimum required version of `npm` and to override certain package versions. 
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L59-R60): The `engines` field now includes a specification for `npm` version `>=8.3.0`. This means that the project now requires at least version `8.3.0` of `npm` to run.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R1125-R1128): The `overrides` field has been added to the `optionalDependencies` section. This field specifies that the versions of `jsrsasign` and `axios` should be `^11.0.0` and `^0.28.0` respectively, overriding any other specified versions.

Dependabot alerts package override

---

src/web/client/common/errorHandler.ts
src/web/client/extension.ts
src/web/client/test/integration/errorHandler.test.ts

This pull request includes changes to the `activate` function in the `src/web/client/extension.ts` file. The changes involve the repositioning of the instantiation of `oneDSLoggerWrapper` with `orgGeo` data fetched from `fetchArtemisData(orgId)`. The instantiation, which was previously done before the `checkMandatoryParameters` function call, is now done after the parameters check.
* [`src/web/client/extension.ts`](diffhunk://#diff-1429bea43439e067ae9056ff3f9f71203533f7d3ca168f0d5469aa1b9a6e0360L95-L97): Moved the instantiation of `oneDSLoggerWrapper` with `orgGeo` data fetched from `fetchArtemisData(orgId)` to after the `checkMandatoryParameters` function call. This change ensures that the logger is instantiated only after the mandatory parameters have been …

[Bug Fix] Initial Load Failure

---

src/common/OneDSLoggerTelemetry/oneDSLogger.ts

This pull request adds functionality to set the userRegion based on the geo if it is defined. If the geo is not defined, it will use the parsed geo instead.

Setting userRegion based on geo if defined, else using parsed geo

---

CHANGELOG.md
gulpfile.mjs
l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf

This pull request primarily updates the Power Platform Extension to a new version and enhances error handling. The most significant changes include updating the `CHANGELOG.md` and `gulpfile.mjs` to reflect the new version, and adding new error messages related to the Power Pages generator in `bundle.l10n.json` and `vscode-powerplatform.xlf`.
Version update:
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3-R7): A new version entry (2.0.31) has been added, indicating the update to pac CLI 1.31.6. More updates for this version are marked as "TBD".
* [`gulpfile.mjs`](diffhunk://#diff-903dd1850ba0ff2ab89df00417e93e86fb7115642c6c876d75ecca7f97c940b0L350-R350): The `cliVersion` constant has been updated from '1.30.7' to '1.31.6', reflecting …

Bump up PAC-CLI version for release

---

src/web/client/dal/fileSystemProvider.ts
src/web/client/telemetry/constants.ts

This pull request primarily focuses on enhancing the telemetry within the `PortalsFS` class in the `fileSystemProvider.ts` file. This is accomplished by recording the start time for the file search operation, and then sending this information, along with the number of files found, to the telemetry service. A new telemetry event named `WEB_EXTENSION_SEARCH_FILE` has also been added to the `telemetryEventNames` enumeration in the `constants.ts` file.
Telemetry enhancements:
* [`src/web/client/dal/fileSystemProvider.ts`](diffhunk://#diff-4ccb3f93d7b25ce5d403b78669157a686dfc23c36f47d684a9bf61c9c92f1385R280-R282): Added code to record the start time before searching for files in the `searchFiles` method of the `PortalsFS` class. This is used to calculate the duration …

Add telemetry for File Search feature

---

package.json
src/web/client/utilities/commonUtil.ts

This pull request primarily focuses on disabling certain features in the `package.json` and `commonUtil.ts` files. The changes include modifying the conditions for displaying certain commands and views in `package.json`, and disabling the co-presence feature in `commonUtil.ts`.
* In `package.json`, the visibility conditions for the commands and views have been altered:
* The "powerPlatform.previewCurrentActiveUsers" command is now never shown, as the condition in the "when" field has been changed from "isWeb && virtualWorkspace" to "never".
* Similarly, the "powerpages.collaborationView" view is now never shown. The condition in the "when" field has been changed from "isWeb && virtualWorkspace" to "never".
* In `src/web/client/utilities/commonUtil.ts`, the co-presence feature has been …

Disable power platform co-presence feature.

---

package-lock.json
package.json
src/common/copilot/dataverseMetadata.ts

This pull request primarily involves changes related to the XML DOM package used in the project. The package has been updated from `xmldom` to `@xmldom/xmldom`. This change has been reflected in the `package.json` file and in the import statement in `src/common/copilot/dataverseMetadata.ts`.
FIX for: https://github.com/microsoft/powerplatform-vscode/security/dependabot/41
Package updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1094-R1095): Removed `@types/xmldom` and `xmldom` from the list of dependencies and added `@xmldom/xmldom` instead. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1094-R1095) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L111 …

Update xmldom package version

---

src/common/OneDSLoggerTelemetry/oneDSLogger.ts
src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts
src/common/OneDSLoggerTelemetry/shortNameMappingToAzureRegion.ts

This pull request includes two changes in the `src/common/OneDSLoggerTelemetry` directory. The changes involve code formatting and removal of extra white space.
* [`src/common/OneDSLoggerTelemetry/oneDSLogger.ts`](diffhunk://#diff-1c7a0bcddd4688b6e489876d4ab1a031b03f1dcf43f9b9725f460df8758606dfL312-R312): The formatting of the `catch` block in the `OneDSLogger` class has been improved for better readability. The curly brace that opens the block has been moved to the same line as the `catch` statement.
* [`src/common/OneDSLoggerTelemetry/shortNameMappingToAzureRegion.ts`](diffhunk://#diff-30b15e3495e5d89dc31bbdedce35971fa1dec6250d90cfc0d44e8a47e279b8e1L197): An extra line of white space at the end of the `geoMappingsToAzureRegion` constant has been removed.Fixed Indentation for couple of …

Indentation Fixed

---

src/web/client/WebExtensionContext.ts
src/web/client/common/worker/webworker.js
src/web/client/context/userDataMap.ts
src/web/client/extension.ts
src/web/client/webViews/QuickPickProvider.ts

This PR addresses a critical bug where removing an instance of a user would inadvertently remove all their presence information from both the page-level and collaborative views. The new approach ensures robust, individual tracking of user instances, optimizing real-time collaboration and presence awareness. 
Enhancement done: user connection data is directly mapped with user IDs. This mapping allows for the precise removal of specific user connections when they are no longer active, without affecting the presence information of other instances or the overarching user presence.

[Bug Fix] All Instance Removed on Removing Single Instance

---

src/web/client/extension.ts

Adding InitParamsEvent in OneDSLogger specifically as it has lot of important information like websiteid, orgId

InitParamsEvent is getting dropped in OneDSLogger

---

.release-it.yaml

This pull request includes a change to the `.release-it.yaml` configuration file. The change adds a hook that is called after the release process, which sets a task variable `PPVSC_VERSION` to the current version. This can be useful for tracking the version of the software in subsequent tasks.

After release publish the release version back to be user in ADO pipeline

---

src/common/copilot/dataverseMetadata.ts

This pull request primarily focuses on the refactoring of the `getEntityColumns` function and related changes in the `src/common/copilot/dataverseMetadata.ts` file. The changes involve the removal of the `Attribute` interface, modification of the `dataverseURL`, and significant changes to the `getAttributesFromResponse` function to return an array of `string` instead of `Attribute` objects.
* [`src/common/copilot/dataverseMetadata.ts`](diffhunk://#diff-f01824da34af02017a75c331f96e8098e03b6d9c20d04bf943d8551fddde621fL18-R22): Removed the `Attribute` interface. This interface was previously used to type the `attributes` variable in the `getEntityColumns` function.
* [`src/common/copilot/dataverseMetadata.ts`](diffhunk://#diff-f01824da34af02017a75c331f96e8098e03b6d9c …

Fetching logical and display name for attributes

---

package-lock.json
package.json

This pull request includes changes to the `package.json` file. The changes update the versions of two dependencies and remove the `overrides` section.
Here are the most important changes:
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1088-R1088): Upgraded the `@fluidframework/azure-client` dependency from version `^1.1.1` to `^1.2.0`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1099-R1099): Upgraded the `fluid-framework` dependency from version `^1.3.3` to `^1.4.0`.
Removal of overrides:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1126-L1129): Removed the `overrides` section which included `jsrsasign` …

copresence package update - remove package version override

---

src/common/copilot/PowerPagesCopilot.ts
src/common/copilot/assets/styles/copilot.css

This pull request includes changes to the user interface and styling of the input field in the `PowerPagesCopilot` class. The main changes involve modifying the input field from a single-line text input to a multi-line textarea, and updating the CSS styles to hide the scrollbar and prevent resizing of the textarea.
User interface changes:
* [`src/common/copilot/PowerPagesCopilot.ts`](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880abL501-R501): Changed the input field from a single-line text input to a multi-line textarea to improve user experience and allow for multi-line input.
Styling updates:
* [`src/common/copilot/assets/styles/copilot.css`](diffhunk://#diff-ec7b77375fce346d1f954661f131d5d22b2ef655615e35652ccd9bf9546466b9L66-R71): Updated the CSS styles …

Multiline support in input box with scroll

---

src/client/extension.ts
src/common/OneDSLoggerTelemetry/oneDSLogger.ts

This pull request includes changes to enhance telemetry logging by including geographical information in the `DESKTOP_EXTENSION_INIT_CONTEXT` event. The changes are primarily in the `src/client/extension.ts` and `src/common/OneDSLoggerTelemetry/oneDSLogger.ts` files.
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL198-R198): Modified the `activate` function to include `orgGeo` (organization's geographical information) in the `DESKTOP_EXTENSION_INIT_CONTEXT` event. This is achieved by extending the `orgDetails` object with `orgGeo` before passing it to `traceInfo` method.
* [`src/common/OneDSLoggerTelemetry/oneDSLogger.ts`](diffhunk://#diff-1c7a0bcddd4688b6e489876d4ab1a031b03f1dcf43f9b9725f460df8758606dfR359): Updated the …

Log OrgGeo for desktop extension

---

src/common/ecs-features/ecsFeatureClient.ts
src/common/ecs-features/ecsTelemetryConstants.ts

This pull request primarily focuses on enhancing telemetry in the `ECSFeaturesClient` class within the `src/common/ecs-features/ecsFeatureClient.ts` file. The changes include the addition of specific telemetry event names and the modification of the telemetry event triggering mechanism.
Telemetry improvements:
* [`src/common/ecs-features/ecsFeatureClient.ts`](diffhunk://#diff-98e08ba3296c95ebe1634a863e99f6b980b26f407301e1ca1bb137a33bff75dcR11): Imported new telemetry event names `ECSConfigFailedInit` and `ECSConfigSuccessfulInit` from `ecsTelemetryConstants` and used them to send telemetry events. Previously, the telemetry events were commented out and were to be updated in a future PR. Now, telemetry events are sent when the ECS config initialization is successful, including the client …

Telemetry for ECS fetch and config read

---

src/web/client/extension.ts
src/web/client/webViews/QuickPickProvider.ts

This pull request refactors the QuickPickProvider class to handle tab input changes. The code changes check if the active tab is an instance of vscode.TabInputCustom or vscode.TabInputText and update the quick pick items based on the file path of the tab input. This improves the functionality of the QuickPickProvider and ensures that the quick pick items are updated correctly when the tab input changes.

Refactor QuickPickProvider to handle custom tab changes also

---

.release-it.yaml

This pull request includes a change to the `.release-it.yaml` configuration file. The `push` setting under `git` has been updated from `false` to `true`. This change alters the behavior of the git operations during the release process, enabling automatic pushing of changes.

Update release it push parameter to true - needs for version tag publish

---

src/common/Utils.ts
src/common/copilot/PowerPagesCopilot.ts

The code changes add a new function called getActiveEditorContent to the Utils module. This function retrieves the content and parameters of the active editor in Visual Studio Code.
This pull request primarily involves changes to the `src/common/Utils.ts` and `src/common/copilot/PowerPagesCopilot.ts` files. The main changes include the addition of new imports in `Utils.ts`, the creation of a new function `getActiveEditorContent()` in `Utils.ts`, and the removal of the `getActiveEditorContent()` method from `PowerPagesCopilot.ts` to use the newly created function from `Utils.ts`. 
Additions and modifications in `src/common/Utils.ts`:
* Added new imports from `./copilot/constants` and `./copilot/model` to include `DataverseEntityNameMap`, `EntityFieldMap`, `FieldTypeMap`, and …

feat: Move getActiveEditorContent function to utils

---

CHANGELOG.md

This pull request includes an update to the `CHANGELOG.md` file. The change adds a new version entry (2.0.49) with details about the updates in the web extension, specifically the support for copresence to show editors/viewers currently present on Power Pages Studio and Power Pages VSCode Extension for Web.

Release notes for April release

---

src/client/extension.ts

This pull request includes changes to the `src/client/extension.ts` file, specifically within the `export async function activate(` function. The changes involve the reordering of the `vscode.workspace.onDidOpenTextDocument(didOpenTextDocument);` and `vscode.workspace.textDocuments.forEach(didOpenTextDocument);` lines. These lines were moved from an earlier part of the function to a later part. 
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL99-L101): The `vscode.workspace.onDidOpenTextDocument(didOpenTextDocument);` and `vscode.workspace.textDocuments.forEach(didOpenTextDocument);` lines were moved from the top of the `activate` function to a spot further down in the function. This reordering have …

Invoking Language Server Only for Power Pages Workspace

---

src/common/copilot/PowerPagesCopilot.ts
src/web/client/extension.ts
src/web/client/telemetry/constants.ts

This pull request primarily focuses on refactoring and improving the codebase of `src/common/copilot/PowerPagesCopilot.ts` and `src/web/client/extension.ts`. The changes include making `environmentId` a mandatory string, removing the optional chaining operator for `environmentId`, modifying how `fetchArtemisData` returns data, and removing an unused telemetry event.
Changes to `src/common/copilot/PowerPagesCopilot.ts`:
* [`let orgID: string;`](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880abL37-R37): Changed `environmentId` from an optional string to a mandatory string. This change implies that `environmentId` will always have a value and cannot be undefined.
* [`export class PowerPagesCopilot implements vscode.WebviewViewProvider …

Update PowerPagesCopilot to initialize EnvId for Desktop extension flow of copilot; Cleanup web extension Artemis calls

---

src/common/copilot/PowerPagesCopilot.ts
src/common/utilities/Utils.ts

This pull request includes a change to the `PowerPagesCopilot` class in the `src/common/copilot/PowerPagesCopilot.ts` file. The change modifies the event handling for `orgChangeErrorEvent` to only push the event to the `_disposables` array when the `_view` property is visible. This change is likely intended to prevent unnecessary event handling when the view is not visible, potentially improving performance.

Auth create flow triggered only when copilot WebView is visible

---

package-lock.json
package.json
src/web/client/webViews/QuickPickProvider.ts

This pull request primarily includes updates to the `package.json` file and a change in the `QuickPickProvider.ts` file. The `package.json` file has been updated to use a newer version of `vscode` and `@types/vscode`. In the `QuickPickProvider.ts` file, the `iconPath` property has been removed from the `IQuickPickItem` interface.
Updates to dependencies:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L59-R59): The `vscode` engine version has been updated from `^1.73.0` to `^1.89.0`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1040-R1040): The `@types/vscode` dependency version has been updated from `^1.73.0` to `^1.89.0`.
Change in `QuickPickProvider.ts`:
* …

chore: Update vscode and @types/vscode dependencies to version 1.89.0

---

src/common/copilot/PowerPagesCopilot.ts
src/common/services/AuthenticationProvider.ts

NOTE wil consider moving to jsonwebtoken to directly get ID post sync with vscode auth contact point.
This pull request primarily focuses on modifying how user IDs are extracted from account IDs in the `AuthenticationProvider.ts` file. The extraction logic has been changed in four different authentication functions. Instead of using `pop()` to get the last segment of the ID after splitting it by '/', the updated code uses `shift()` to get the first segment after splitting the ID by either '.' or '/'.
Here are the primary changes:
* `src/common/services/AuthenticationProvider.ts` - `intelligenceAPIAuthentication` function: Updated the extraction of `userId` from `session?.account.id` by splitting it with a regular expression and using `shift()` instead of `pop()`.
* …

UserId fix for malformed ID read from auth sessions

---

src/web/client/dal/remoteFetchProvider.ts
src/web/client/telemetry/constants.ts
src/web/client/utilities/commonUtil.ts

This pull request primarily focuses on the `src/web/client/dal/remoteFetchProvider.ts` and `src/web/client/utilities/commonUtil.ts` files. The changes involve the replacement of the `NO_CONTENT` constant with checks for null or undefined values, the addition of error handling in the `preprocessData` function, and the inclusion of a new telemetry event.
**Refactoring and Error Handling:**
* [`src/web/client/dal/remoteFetchProvider.ts`](diffhunk://#diff-3bdc6b0be6c5885d51a3c8dea2d155cd6c1ab149514f5f75b477a401245493feL336-R337): Replaced checks against `NO_CONTENT` with `isNullOrUndefined` checks in the `processDataAndCreateFile` and `preprocessData` functions. This change improves the robustness of the code by handling null or undefined values more explicitly. …

Handle multi step form with bad step data

---

src/client/PortalWebView.ts
src/client/extension.ts
src/common/utilities/PathFinderUtil.ts
src/common/utilities/WorkspaceInfoFinderUtil.ts
src/server/YamlServer.ts
src/server/lib/PortalManifestReader.ts

key issue: Language server refers to common module files - which in turn is incorrectly referring to desktop client file which were causing import of "vscode" module in Language server code. Importing vscode module in langugae server is not a supported sceanrio - hence a crash here.
This is related to issue [#893](https://github.com/microsoft/powerplatform-vscode/issues/893)
Under the line copilot generated text:
------------------------------------------
This pull request primarily involves refactoring and reorganizing the codebase. The changes include the renaming of a file and the relocation of functions, with modifications to the corresponding import statements. The most significant changes are:
File renaming and function relocation:
* `src/common/PortalConfigFinder.ts` has been …

Fix HTML/YML server crash issue

---

package-lock.json
package.json

This pull request contains updates to the `package.json` file. The changes are primarily focused on updating the versions of `vscode` and `@types/vscode` from `^1.89.0` to `^1.91.0`. 
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L59-R59): Updated the version of `vscode` from `^1.89.0` to `^1.91.0` in the `engines` section. This change indicates that the extension now requires at least version 1.91.0 of Visual Studio Code to run.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1040-R1040): Updated the version of `@types/vscode` from `^1.89.0` to `^1.91.0` in the `devDependencies` section. This change updates the TypeScript definitions for the Visual Studio …

chore: Update vscode and @types/vscode dependencies to latest versions

---

src/common/OneDSLoggerTelemetry/web/client/webExtensionTelemetryEvents.ts
src/web/client/common/errorHandler.ts
src/web/client/test/integration/errorHandler.test.ts

This pull request primarily focuses on enhancing error handling in the `src/web/client/common/errorHandler.ts` file and adding new telemetry event names in the `src/common/OneDSLoggerTelemetry/web/client/webExtensionTelemetryEvents.ts` file. 
The key changes include the addition of two new telemetry event names, a new function `isDynamicsCRMUrl()`, and updates to the `checkMandatoryQueryParameters()` function to include a check for a valid Dynamics CRM URL. Here's a breakdown of the changes:
New telemetry event names:
* [`src/common/OneDSLoggerTelemetry/web/client/webExtensionTelemetryEvents.ts`](diffhunk://#diff-bb82f8809651a816e21902e2dbbd2e27cba15ea568c21a1a7183ceb00cfa70acR77-R78): Two new telemetry event names `WEB_EXTENSION_MULTI_FILE_INVALID_DATAVERSE_URL` and …

Check Dataverse Org URL for validity

---

src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipantUtils.ts
src/common/constants.ts
src/common/copilot/IntelligenceApiService.ts
src/common/copilot/constants.ts
src/common/utilities/Utils.ts

This pull request introduces several enhancements to the `PowerPagesChatParticipant` class and related utilities, focusing on managing and fetching related files for a given context. The most important changes include adding support for fetching related files based on the active file's context, updating schemas for file extensions, and modifying API requests to include related files.
Enhancements to file management:
* [`src/common/utilities/Utils.ts`](diffhunk://#diff-bf8425ddaf7889e68044eb87abc71b32754d10ce9a306723063cf231b01f590cR223-R294): Added functions `getFileContent`, `getFileContentByType`, and `fetchRelatedFiles` to manage and fetch related files based on the active file's context.
Schema updates:
* [`src/common/constants.ts`](diffhunk://#diff-118a1ed2ebf5b946c94c5dfeae1c4d13c9a5 …

[@Powerpages Copilot] Context Improvement for Webpage

---

src/web/client/extension.ts

Bug: https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/4312228
In the web version of VS Code, the authentication prompt currently appears twice during launch. The first prompt is triggered by the powerPagesNavigation function, which internally calls powerPlatformAPIAuthentication with a scope limited to api.powerplatform. The second prompt occurs when readDirectory is invoked, as it uses dataverseAuthentication internally with a broader default scope.
The issue arises because when the user is first authenticated through powerPlatformAPIAuthentication, the session created is not recognized by dataverseAuthentication due to the scope limitations. However, if the user is authenticated with dataverseAuthentication first, the resulting session is recognized by …

BugItem-4312228: changed the reorder of powerpagesNavigation

---

gulpfile.mjs

The PR contains the following changes:
1. Adds Power_Platform_Tools_Feed feed to the supported feeds.
2. Introduces a new pipeline argument 'useFeed' that can be used to choose to Nuget Feed during build.

Add Power_Platform_Tools_Feed to supported Nuget feeds.

---

src/client/extension.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipantConstants.ts
src/common/copilot/constants.ts
src/web/client/extension.ts

This pull request includes several changes to the `extension.ts` and `constants.ts` files to introduce version-based notifications for the Copilot feature. The main changes involve adding new constants, updating imports, and implementing logic to show notifications based on the extension version.
* Added logic to show the Copilot notification panel on the first load or after an update by comparing the stored version with the current version in `function showNotificationForCopilot` in `src/client/extension.ts`.
* Added similar version-based notification logic in `function showNotificationForCopilot` in `src/web/client/extension.ts`.
* Added `EXTENSION_VERSION_KEY` and `EXTENSION_ID` constants to `src/common/copilot/constants.ts`.
* Updated imports to include `EXTENSION_VERSION_KEY` and …

Loading Copilot Notification Panel Ext. Version Update

---

src/client/extension.ts
src/common/ecs-features/ecsFeatureClient.ts

This pull request includes several changes to improve the functionality and maintainability of the codebase. The key modifications involve reordering code for better readability, adding a new parameter to a function call, and updating method signatures to include an optional `force` parameter.
Code reordering and readability improvements:
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL188-L191): Moved the `workspaceFolders` initialization to a more appropriate location for better readability. [[1]](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL188-L191) [[2]](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaR225-R229)
Function call updates:
* …

ECS Initialization fix for desktop on Org Switch

---

src/common/copilot/PowerPagesCopilot.ts
src/common/copilot/telemetry/telemetryConstants.ts
src/common/copilot/welcome-notification/CopilotNotificationPanel.ts

This pull request focuses on enhancing telemetry for GitHub Copilot interactions within the PowerPages extension. The main changes include adding new telemetry events to track the opening of the GitHub Copilot Chat panel and handling cases where the extension is not found.
* [`src/common/copilot/PowerPagesCopilot.ts`](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880abL18-R18): Added telemetry events `VSCodeExtensionGitHubChatPanelOpened` and `VSCodeExtensionGitHubChatNotFound` to track user interactions when opening the GitHub Copilot Chat panel or when the extension is not found. [[1]](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880abL18-R18) [[2]](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880 …

Refactor telemetry constants and add GitHub Copilot integration and external link event

---

src/client/extension.ts

This pull request includes several changes to the `activate` function in the `src/client/extension.ts` file, focusing on initializing the `OrgChangeNotifier` instance and managing the Copilot notification. The most important changes include the initialization of the `OrgChangeNotifier`, handling the Copilot notification, and ensuring that the workspace folders are correctly processed.
Initialization and Notifications:
* Added initialization of the `OrgChangeNotifier` instance with `pacTerminal.getWrapper()`. (`src/client/extension.ts`, [src/client/extension.tsR190-R200](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaR190-R200))
* Introduced a flag `copilotNotificationShown` to ensure the Copilot notification is shown only once. (`src/client/extension.ts`, …

Refactor OrgChangeNotifier and Copilot Notification

---

gulpfile.mjs
src/web/client/WebExtensionContext.ts
src/web/client/extension.ts
src/web/client/telemetry/webExtensionTelemetry.ts
src/web/client/test/integration/webExtensionTelemetry.test.ts
src/web/client/utilities/commonUtil.ts

This pull request includes updates to the `WebExtensionContext` class to support new organizational and environment identifiers, as well as some refactoring and minor version updates. The most important changes include adding new properties for `organizationId` and `environmentId`, updating the `gulpfile.mjs` with a new CLI version, and refactoring telemetry logging.
* Added `organizationId` and `environmentId` properties to the `IWebExtensionContext` interface and the `WebExtensionContext` class. (`src/web/client/WebExtensionContext.ts`) [[1]](diffhunk://#diff-e1e4b1cfb30bca61f70c080e4150842da2a4f1837346604bc23ac58a820ad1caR76-R77) [[2]](diffhunk://#diff-e1e4b1cfb30bca61f70c080e4150842da2a4f1837346604bc23ac58a820ad1caR116-R117) [[3]](diffhunk://#diff-e1e4b1cfb30bca61f70c080e4150842da2a4f1 …

Pac-cli bump up, envId changes and telemetry update

---

src/client/lib/GeneratorAcquisition.ts

https://github.com/microsoft/powerplatform-vscode/issues/1018
The error was caused by a security update in Node.js.
From that blog:
_It is important to note that there has been a breaking change for Windows users who utilize child_process.spawn and child_process.spawnSync. Node.js will now error with EINVAL if a .bat or .cmd file is passed to child_process.spawn and child_process.spawnSync without the shell option set. If the input to spawn/spawnSync is sanitized, users can now pass { shell: true } as an option to prevent the occurrence of EINVALs errors._

Refactor npm command in GeneratorAcquisition to support nodeJs Security Update

---

src/common/chat-participants/CommandRegistry.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts

This pull request introduces a new command registry system to handle command executions within the chat participants module. The key changes include the creation of the `CommandRegistry` class, its integration into the `PowerPagesChatParticipant` class, and the implementation of command execution logic.
* [`src/common/chat-participants/CommandRegistry.ts`](diffhunk://#diff-3cdf8a2bd8d5fc3ebb86d65b45f3fb036d8cb83f0628239dd879f99d7c7a202bR1-R23): Added a new `CommandRegistry` class to manage command registrations and retrievals. This includes an interface `Command` for defining command execution.
* [`src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts`](diffhunk://#diff-885f58fd5bd7ee590ddae0f7854d056026aff9b576864e07f61887fb7586da29R25-R29): Imported and initialized the …

Refactor PowerPagesChatParticipant and add CommandRegistry

---

src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipantConstants.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipantTelemetryConstants.ts
src/common/chat-participants/powerpages/commands/create-site/Nl2PageService.ts
src/common/chat-participants/powerpages/commands/create-site/Nl2SiteService.ts

This pull request introduces new constants and services to handle NL2Page and NL2Site requests in the Power Pages chat participant feature. The most important changes include the addition of new constants, creation of the `getNL2PageData` and `getNL2SiteData` functions, and the integration of telemetry for error tracking and success events.
* [`src/common/chat-participants/powerpages/PowerPagesChatParticipantConstants.ts`](diffhunk://#diff-0b8d35efc4455b9b6e562130d5c35e7d2f87c4bf9635332fbfe408f939d414edR45-R46): Added constants for NL2Page and NL2Site request statuses and error messages. [[1]](diffhunk://#diff-0b8d35efc4455b9b6e562130d5c35e7d2f87c4bf9635332fbfe408f939d414edR45-R46) [[2]](diffhunk://#diff-0b8d35efc4455b9b6e562130d5c35e7d2f87c4bf9635332fbfe408f939d414edL60-R65)
* …

[PowerPage][Copilot] Nl2Site and Nl2Page Service Integration for Site Create

---

gulpfile.mjs

This pull request includes a version update to the `gulpfile.mjs` file. The `cliVersion` constant has been updated to reflect the latest version.
* [`gulpfile.mjs`](diffhunk://#diff-903dd1850ba0ff2ab89df00417e93e86fb7115642c6c876d75ecca7f97c940b0L358-R358): Updated `cliVersion` from '1.35.1' to '1.37.4' to ensure compatibility with the latest CLI features and fixes.

Bump CLI version from 1.35.1 to 1.37.4

---

package.json

Removing the command `extension.createChatView` from package.json as it is registered but there is no handler associated with it.

Remove unused command from package.json

---

src/web/client/dal/concurrencyHandler.ts

This PR is correcting the error thrown when the request fails due to `BulkheadRejectedError`. 
The error currently thrown is `SUBURI_EMPTY` which is a typo and should be `BULKHEAD_LIMITS_EXCEEDED`.

Fix error type for concurrency handler

---

.gitignore

Adding the code coverage output folder `.nyc_ouput` folder in `.gitignore` so that it doesn't show up in `git diff` after running code coverage command.

Add code coverage output folder in gitignore

---

src/client/extension.ts
src/client/lib/CliAcquisition.ts
src/client/lib/CliAcquisitionContext.ts
src/client/lib/GeneratorAcquisition.ts
src/client/test/Integration/CliAcquisition.test.ts
src/client/test/Integration/CliAcquisitionContext.test.ts

1. Moved the `CliAcquisitionContext` class in its own file to improve code modularity. The file is not required to be in `extension.ts`.
2. Moved `ICliAcquisitionContext` also to `CliAcquisitionContext.ts` file so that the interface and its implementation is collocated.
3. Added tests for `CliAcquisitionContext`

Refactor CLI Acquisition Context

---

src/common/copilot/PowerPagesCopilot.ts

Fix accessibility issue in `Send` button in Power Pages Copilot pane. Updated the `aria-label` to `Send` instead of `Match Case`

Fix accessibility issue in Pages Copilot pane

---

gulpfile.mjs

The step `testWeb` is redundant as the step `testUnitTests` already includes the test pattern defined in `testWeb` step. Hence, removing it from gulp config.

Remove redundant testWeb step from gulp file

---

package.json
src/client/extension.ts

Currently there are 2 `Preview Site` commands shown in command palette. However, one of them is only functional in vscode.dev and doesn't work when invoked from command palette so it can be hidden. The other command should only be shown when the feature is enabled.
1. Removed `powerpages.powerPagesFileExplorer.powerPagesRuntimePreview` from command palette.
2. Added a `when` clause for `microsoft.powerplatform.pages.preview-site` command to only show when the feature is enabled.

Hide preview site command from palette when feature is disabled

---

src/web/client/dal/remoteFetchProvider.ts
src/web/client/schema/portalSchema.ts
src/web/client/utilities/commonUtil.ts

This pull request includes changes to handle cases where language codes are null for content snippets and updates to query parameters in portal schemas. The main changes involve error handling, default language code assignment, and query parameter adjustments.
Error handling and default language code assignment:
* [`src/web/client/dal/remoteFetchProvider.ts`](diffhunk://#diff-3bdc6b0be6c5885d51a3c8dea2d155cd6c1ab149514f5f75b477a401245493feR249-L253): Modified the `createContentFiles` function to handle cases where the language code is null for content snippets by assigning a default language code.
* [`src/web/client/utilities/commonUtil.ts`](diffhunk://#diff-0571fa597154eb22907e2fbbd10adc9ccc04cba979a11f3c571f94a54abcf179R46-R57): Updated the `GetFileNameWithExtension` function to handle …

[PowerPages][vscode.dev] Showing Content Snippets Not Having Language Record

---

src/common/copilot/assets/scripts/copilot.js

This pull request focuses on improving accessibility in the `src/common/copilot/assets/scripts/copilot.js` file. The changes include adding `aria-label` attributes to various elements and implementing keyboard accessibility for interactive components.
Accessibility improvements:
* Added `aria-label` attributes to `copyButton`, `insertButton`, `suggested-prompt`, `walkthrough-content`, and `loginButton` to improve screen reader support. [[1]](diffhunk://#diff-2b752bc47b9599a39d91a02dc72fc16cc92edad87ef510294403fdc46306e07dR137) [[2]](diffhunk://#diff-2b752bc47b9599a39d91a02dc72fc16cc92edad87ef510294403fdc46306e07dR148-L152) [[3]](diffhunk://#diff-2b752bc47b9599a39d91a02dc72fc16cc92edad87ef510294403fdc46306e07dL262-R276) [[4]](diffhunk://#diff-2b752bc47b9599a39d91a02dc72fc16cc92edad87ef51029 …

[ProDev Copilot] Enhance accessibility by adding ARIA attributes and keyboard navigation

---

src/common/copilot/assets/scripts/copilot.js

This pull request includes an accessibility improvement to the `src/common/copilot/assets/scripts/copilot.js` file. The change ensures that the "thinking" element is focusable and properly announced by screen readers.
Accessibility improvements:
* [`src/common/copilot/assets/scripts/copilot.js`](diffhunk://#diff-2b752bc47b9599a39d91a02dc72fc16cc92edad87ef510294403fdc46306e07dR320-R322): Added `tabindex`, `role`, and `aria-live` attributes to the "thinking" element to improve focusability and screen reader support.

Enhance accessibility by adding ARIA attributes and making thinking message focusable

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
src/client/preview-site/Constants.ts
src/client/preview-site/PreviewSite.ts
src/common/services/TelemetryConstants.ts

This pull request enhances the `PreviewSite` functionality by adding error handling, cache clearing, and telemetry logging. The changes include updates to constants, imports, and the `PreviewSite` class to support these new features.
Error handling and telemetry logging:
* [`src/client/preview-site/Constants.ts`](diffhunk://#diff-b4c9372dc8b130e14a8674f379284867a03a2734bc3f9df39d523b378eb5fda4L23-R27): Added new messages for various errors and actions such as `ORG_DETAILS_ERROR`, `CLEARING_CACHE`, `AUTHENTICATING`, and `UNABLE_TO_CLEAR_CACHE`.
* [`src/common/services/TelemetryConstants.ts`](diffhunk://#diff-6faf798b4f5991fb9736b5948319d0a8f3e94926cc41141a2b59e602da3c7892R33): Added a new telemetry constant `VSCODE_EXTENSION_SITE_PREVIEW_ERROR` to log site preview errors.
* …

Site Preview Enhancements: Clear cache and telemetry logging

---

src/web/client/dal/fileSystemProvider.ts

Using `vscode.open` API to open the default file instead of `window.showTextDocument` because `showTextDocument` doesn't open binary files to it was failing to open non-text files.

Web Extension: Fix file opening for media files

---

gulpfile.mjs

This pull request includes a small change to the gulpfile.mjs file. The change updates the cliVersion constant to the latest version.

Bump CLI version from 1.37.4 to 1.39.3

---

src/client/extension.ts
src/client/power-pages/preview-site/PreviewSite.ts

This pull request includes several changes to the `src/client/extension.ts` and `src/client/power-pages/preview-site/PreviewSite.ts` files to refactor and improve the functionality related to site runtime preview and initialization.
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaR51): Added `IArtemisServiceResponse` import to the file.
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL196-L199): Removed direct calls to `PreviewSite.isSiteRuntimePreviewEnabled` and `PreviewSite.loadSiteUrl`, and instead created a new function `initializeSiteRuntimePreview` to handle these operations. [[1]](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664 …

Site Preview: Initialize after ECS fetch

---

src/common/copilot/user-feedback/CESSurvey.ts

This pull request includes minor changes to the `getWebviewContent` function in the `src/common/copilot/user-feedback/CESSurvey.ts` file. The changes focus on improving accessibility and cleaning up the code.
Accessibility improvement:
* Added a `tabindex="0"` attribute to the submit button to ensure it can be focused using the keyboard.
Code cleanup:
* Removed an unnecessary blank line after the `useEUEndpoint` function.

Fix A11y bug related to keyboard focus

---

src/client/extension.ts
src/client/pac/PacAuthManager.ts
src/client/power-pages/actions-hub/ActionsHub.ts
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/power-pages/preview-site/PreviewSite.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHub.test.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts
src/common/ecs-features/ecsFeatureGates.ts

This pull request includes several important changes to the `src/client` and `src/common` directories to improve the initialization and feature flag handling for the Actions Hub and Site Runtime Preview functionalities.
* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL255-R257): Moved the initialization logic for the Site Runtime Preview and Actions Hub into their respective classes (`PreviewSite` and `ActionsHub`). This change simplifies the `activate` function and ensures that feature flags are checked within their relevant classes. [[1]](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL255-R257) [[2]](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL279-L280) …

Actions Hub: Add toggle based on ECS

---

src/client/power-pages/preview-site/PreviewSite.ts

This pull request includes changes to the `PreviewSite` class in the `src/client/power-pages/preview-site/PreviewSite.ts` file. The main focus of these changes is to simplify the code and improve error handling.
Code simplification:
* Simplified the `showProgressWithNotification` method to directly pass the `launchUrl` parameter to the `vscode-edge-devtools.launch` command.
Error handling improvements:
* Changed the error handling logic for the `clearCacheResponse` to use `response.text()` instead of `response.json()` to avoid potential issues with non-JSON responses.

[PowerPages] [Site Preview] Simplify preview functionality

---

webpack.config.js

This pull request includes changes to the `webpack.config.js` file to handle specific warnings more effectively. The most important changes include adding an `ignoreWarnings` configuration to various webpack configurations.
Changes to handle warnings:
* [`webpack.config.js`](diffhunk://#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR59-R63): Added `ignoreWarnings` configuration to `nodeConfig` to ignore warnings related to dynamic dependencies.
* [`webpack.config.js`](diffhunk://#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR128-R132): Added `ignoreWarnings` configuration to `webConfig` to ignore warnings related to dynamic dependencies.
* [`webpack.config.js`](diffhunk://#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR1 …

Webpack: Ignore warnings

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/power-pages/actions-hub/Constants.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts

This pull request introduces a new feature that allows users to switch environments within the Power Pages Actions Hub. It includes updates to localization files, command registration, and test cases to support this new functionality.
Key changes include:
* **Localization Updates:**
- Added the string "Select an environment to switch to" to `l10n/bundle.l10n.json` and `loc/translations-export/vscode-powerplatform.xlf`. [[1]](diffhunk://#diff-829b512e02461234524c007941f3260e67a43b109f48bedf257ab8e8033cc527R185) [[2]](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R427-R429)
- Updated `package.nls.json` to include the title for the new switch environment command.
* **Command Registration:**
- Added the `powerpages.actionsHub.switchEnvironment` command in …

[PowerPages][Actions Hub] Toggle to Change Environment

---

loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/power-pages/actions-hub/CurrentSiteContext.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts

This pull request introduces several new features and improvements to the Power Platform extension, focusing on enhancing the user interface and functionality for revealing the current active site in the operating system's file explorer. The main changes include adding new commands for different operating systems, updating the context handling for the current site, and adding tests for the new functionality.
New commands and context handling:
* Added new commands for revealing the current active site in Windows Explorer, macOS Finder, and Linux file manager in `package.json`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R422-R433) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R898-R909) …

[Power Pages][Actions Hub] Add revealInOS command for current active site

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/power-pages/actions-hub/Constants.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts

1. Introduce a new command for displaying site details, including friendly name, website ID, and data model version.
2. Implement error handling for the site management URL and add corresponding tests.

[Power Pages][Actions Hub] Add site details command

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/power-pages/actions-hub/Constants.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts

Introduce a new command to download the current site, including user prompts for folder selection and command execution. Update localization strings and register the command in the Actions Hub.
> [!NOTE]
> When the site is `current` then the download location will be automatically picked up.

[Power Pages] [Actions Hub] Add download site command to Actions Hub

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
package.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/Constants.ts
src/client/power-pages/actions-hub/models/IWebsiteInfo.ts
src/client/power-pages/actions-hub/tree-items/OtherSitesGroupTreeItem.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/common/copilot/dataverseMetadata.ts

This pull request includes several changes to enhance the functionality of the Actions Hub in Power Pages. The key changes involve adding support for uploading sites that are not in the current environment, improving error handling, and adding new constants for better code readability and maintainability.
* [`src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts`](diffhunk://#diff-1ab9691ce442179f489ba49f832a1f872247015667f1e1eab3bc8f027d457fc2R255-R349): Added new functions `uploadOtherSite` and `uploadCurrentSite` to handle uploads for sites not in the current environment and active/inactive sites, respectively. Improved error handling and added logging for upload attempts and failures.
* [`src/client/power-pages/actions-hub/Constants.ts`](diffhunk://#diff-f5975640a34750e7cb7a2 …

[PowerPages][ActionsHub] Upload functionality for other sites

---

loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts

This pull request introduces a new feature to open sites in the Power Pages Studio, along with some code refactoring and test updates to support this functionality. The most important changes include additions to the `package.json` and `package.nls.json` files, modifications to the `ActionsHubCommandHandlers.ts` file, and updates to the test files.
New feature implementation:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R450-R453): Added new command `microsoft.powerplatform.pages.actionsHub.activeSite.openInStudio` in multiple sections to support opening sites in Power Pages Studio. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R450-R453) …

[Power Pages] [Actions Hub] Add 'Open in Power Pages Studio' command

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
src/client/extension.ts
src/client/pac/PacWrapper.ts
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/preview-site/Constants.ts
src/client/power-pages/preview-site/PreviewSite.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts
src/client/test/Integration/power-pages/preview-site/PreviewSite.test.ts
src/common/constants.ts

This pull request introduces several changes to enhance the functionality and maintainability of the `PreviewSite` class and related components. The changes include adding new methods, updating existing methods to handle additional parameters, and modifying constants and test cases to support these updates.
* Added a new method `pendingChanges` to the `PacWrapper` class to check for pending changes on a website (`src/client/pac/PacWrapper.ts`).
* Updated the `initialize` method of the `PreviewSite` class to accept a `PacTerminal` parameter and store it for later use (`src/client/power-pages/preview-site/PreviewSite.ts`).
* Modified the `launchBrowserAndDevToolsWithinVsCode` method to take an additional `dataModelVersion` parameter and show a warning if there are pending changes …

[Power Pages][Preview Site] Show notification when previewing site with pending changes

---

package.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts

This pull request includes several changes to enhance the functionality of the `revealInOS` command and update the associated tests. The most important changes include modifying the command conditions in `package.json`, updating the `revealInOS` function to handle multiple site contexts, and adding new tests to cover these scenarios.
Enhancements to command functionality:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1095-R1105): Updated the conditions for `revealInOS` commands to handle both `currentActiveSite` and `otherSite` for Windows, Mac, and Linux.
Updates to `revealInOS` function:
* [`src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts`](diffhunk://#diff-1ab9691ce442179f489ba49f832a1f872247015667f1e1eab3bc8f027d457 …

[Power Pages] [Actions Hub] Enhance revealInOS command to support others ites

---

src/client/extension.ts

This pull request includes updates to the `src/client/extension.ts` file to improve the initialization process and conditional logic for showing notifications. The key changes are:
Initialization improvements:
* Added initialization of the `OrgChangeNotifier` instance earlier in the `activate` function to ensure it is set up before any potential organization changes are handled.
Conditional logic updates:
* Modified the condition for showing the copilot notification to include a check for the presence of a portal configuration folder in the workspace. This ensures that the notification is only shown when relevant.
Showing ActionsHub for non-Pages workspace:

[Power Pages] [Actions Hub] Initialize Actions Hub for all workspaces

---

src/client/power-pages/actions-hub/tree-items/ActionsHubTreeItem.ts
src/client/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.ts
src/client/test/Integration/power-pages/actions-hub/tree-items/ActionsHubTreeItem.test.ts
src/client/test/Integration/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.test.ts

This pull request includes changes to the `ActionsHubTreeItem` class and its related tests to handle cases where the label is `null` or `undefined`. The most important changes include updating the constructor of `ActionsHubTreeItem` and adding a new test case to verify the behavior when a `null` label is passed.
Changes to `ActionsHubTreeItem` class:
* [`src/client/power-pages/actions-hub/tree-items/ActionsHubTreeItem.ts`](diffhunk://#diff-61c419179c9505d75e74089dd975a22c3f4c8af7d128efef523ca364c3bbb895L10-R18): Modified the constructor to accept `label` as `string | null | undefined` and updated the `tooltip` assignment to handle `null` or `undefined` labels.
Updates to tests:
* [`src/client/test/Integration/power-pages/actions-hub/tree-items/ActionsHubTreeItem.test.ts`](diffhunk://#diff- …

[Power Pages] [Actions Hub] Handle null or undefined labels in ActionsHubTreeItem

---

src/client/test/Integration/validationDiagnostics.test.ts

- ✏️ Corrected spelling of "Pattern" in test names
- 🔧 Updated file path handling to use vscode.Uri.file
- 📂 Simplified file path construction for better readability

[Power Pages] Fix typos and improve file path handling in tests

---

src/common/copilot/user-feedback/feedback.css

- ✨ Removed the outline property from button styles for improved accessibility.
Color contrast ratio of outline

Remove outline from feedback button styles

---

src/common/OneDSLoggerTelemetry/oneDSLogger.ts
src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts

- ✏️ Corrected spelling of 'initialize' in OneDSLogger and oneDSLoggerWrapper classes
- 🔧 Updated variable name from 'oneDSLoggerIntance' to 'oneDSLoggerInstance' for consistency

Fix typos in OneDSLogger and oneDSLoggerWrapper

---

src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts

This pull request includes a change to the `fetchWebsites` function in `src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts`. The change adds a sorting mechanism for `activeWebsiteDetails` based on the `createdOn` date, ensuring newly created sites appear at the top.
* [`src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts`](diffhunk://#diff-1ab9691ce442179f489ba49f832a1f872247015667f1e1eab3bc8f027d457fc2R238-R242): Added sorting for `activeWebsiteDetails` based on the `createdOn` date.
[Bug 4767957](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/4767957): [Actions Hub] The order of the site lists in 'Active Sites' and 'Inactive Sites' appears different in VsCode compared to PP Home.

[Powerpages][ActionsHub]Sort active websites by creation date in fetchWebsites function

---

src/client/test/Integration/WebsiteUtil.test.ts
src/common/utilities/WebsiteUtil.ts

Introduce unit tests for the `getActiveWebsites` function to ensure correct behavior and error handling. Update the `getAppModules` function to accept an `accessToken` parameter, ensuring proper token usage across related API calls.

[Power Pages][Actions Hub] Add unit tests

---

src/client/power-pages/preview-site/Constants.ts
src/client/power-pages/preview-site/PreviewSite.ts

- 🔧 Added a method to close existing Edge DevTools tabs before launching a new preview.
- 🚀 Updated the site preview command to ensure no duplicate DevTools instances are open.

[Power Pages][Preview] Close existing Edge DevTools before launching preview

---

loc/translations-export/vscode-powerplatform.xlf
package.json
package.nls.json
src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/power-pages/actions-hub/Constants.ts

- Introduced a new configuration option for specifying the download site folder.
- Added a description for the download site folder setting in localization files to enhance user understanding.
- Updated logic to check for a configured download path in the ActionsHub command handlers, improving user experience when downloading sites.

feat(actions-hub): Add download site folder configuration

---

l10n/bundle.l10n.json
loc/translations-export/vscode-powerplatform.xlf
src/client/PortalWebView.ts

- 🔄 Replace `searchPortalConfigFolder` with `findWebsiteYmlFolder` for improved folder detection.
- 🔧 Update logic to handle active text editor and reveal the panel correctly.

[Power Pages] Refactor PortalWebView to use new utility function

---

package.json
src/client/extension.ts

Introduce a new context for command execution during the activation process and organization change error handling.
This ensures that the buttons remain disabled until the environment is initialized and the actions hub is ready to be used.

Add environment initialization context for command execution

---

src/common/copilot/user-feedback/feedback.css

This PR contains the necessary CSS changes to add an outline around the 'privacy details' link when focused.

Fix A11y Issue In Feedback Panel

---

src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts
src/common/chat-participants/powerpages/PowerPagesChatParticipantUtils.ts

This pull request refactors the `PowerPagesChatParticipant` class to optimize endpoint management by introducing caching and an initialization method. The changes aim to reduce redundant calls to `getEndpoint` and improve error handling for endpoint initialization.
* Added a private `initializeEndpoint` method to handle endpoint initialization and caching. This method ensures that the endpoint is only fetched when necessary and validates its availability.
* Updated the logic to use `this.cachedEndpoint` instead of repeatedly calling `getEndpoint` for every request, reducing unnecessary API calls. [[1]](diffhunk://#diff-885f58fd5bd7ee590ddae0f7854d056026aff9b576864e07f61887fb7586da29L122-R137) [[2]](diffhunk://#diff-885f58fd5bd7ee590ddae0f7854d056026aff9b576864e07f61887fb7586da29L165-R170) …

[PowerPages][GitHub Copilot] Refactor endpoint initialization logic to use cached data and improve efficiency

---

src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts
src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts

This pull request updates the behavior of the `getStudioBaseUrl` function and its associated test cases to align the pre-production (`PREPROD`) environment with the test (`TEST`) environment in the Power Pages Actions Hub.
* In `src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts`, the `getStudioBaseUrl` function was updated to return the test environment URL for the `PREPROD` environment, ensuring consistency between the two environments.
* In `src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts`, updated the expected URLs in test cases for `openActiveSitesInStudio` and `openInactiveSitesInStudio` to reflect the new behavior of using the test environment URL for the `PREPROD` environment. …

Fix: Update preprod studio endpoint to use test endpoint

---

CHANGELOG.md

This pull request updates the `CHANGELOG.md` file to document the release of version 2.0.86 of the Power Platform Extension.
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3-R7): Added an entry for version 2.0.86, which includes an update to `pac CLI` version 1.43.6 and a bug fix for the authentication flow in Copilot experiences on desktop.

Update CHANGELOG for pac CLI 1.43.6 release and authentication flow fix

---

src/client/extension.ts
src/common/OneDSLoggerTelemetry/oneDSLogger.ts
src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts
src/common/OneDSLoggerTelemetry/telemetryConstants.ts
src/web/client/extension.ts

This pull request introduces enhancements to the telemetry logging system by adding support for environment-specific configurations. The changes ensure that the logging system can handle different environments (e.g., preprod, test) and adapt instrumentation settings accordingly. Additionally, minor adjustments were made to improve code clarity and maintainability.
* Added an `environment` parameter to the `OneDSLogger` constructor and related methods, allowing environment-specific configurations to be passed and used for telemetry logging. (`src/common/OneDSLoggerTelemetry/oneDSLogger.ts`: [[1]](diffhunk://#diff-1c7a0bcddd4688b6e489876d4ab1a031b03f1dcf43f9b9725f460df8758606dfL87-R88) [[2]](diffhunk://#diff-1c7a0bcddd4688b6e489876d4ab1a031b03f1dcf43f9b9725f460df8758606dfL97-R98) …

Fix Telemetry: Send telemetry for non-prod environments to test cluster

---

src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts

This pull request includes a small change to the `reactivateSite` function in the `ActionsHubCommandHandlers.ts` file. The change ensures that the `siteAddress` variable is set to an empty string if `websiteUrl` is `null` or `undefined`, preventing potential issues with URL construction.

fix: handle null or undefined siteAddress in reactivateSite URL construction

---

CHANGELOG.md

This pull request updates the `CHANGELOG.md` file to document the release of version 2.0.91 of the Power Platform Extension. The changes include an update to the pac CLI version and fixes for two bugs.
* Updated to pac CLI version 1.45.3.
* Resolved an issue where active sites were incorrectly displayed as inactive in Power Pages Actions for Sovereign Clouds.
* Fixed a bug causing page duplication in Visual Studio Code web.

[July Release] Update CHANGELOG for pac CLI 1.45.3 and bug fixes in Power Pages Actions

---

src/web/client/dal/remoteFetchProvider.ts
src/web/client/schema/constants.ts

This pull request refactors how webpage content files are organized and created, specifically improving folder naming and handling for duplicate webpage names by grouping them based on their root webpage ID. The changes ensure more consistent and collision-free folder structures when exporting webpages, and enhance telemetry tracking for duplicate folder scenarios.
**Webpage folder organization improvements:**
* Webpage folders are now grouped and named by their root webpage ID, using a combination of the file name and root webpage ID to avoid naming collisions and ensure consistent folder naming.
* The logic for detecting and handling duplicate webpage folder names has been moved from `createContentFiles` to `processDataAndCreateFile`, and expanded to support grouping by root webpage ID. …

Refactor createContentFiles and processDataAndCreateFile to improve folder name handling for webpages

---

localize/LocProject.json

Add the loc manifest file to define the scope of the new loc process. Please refer to https://eng.ms/docs/cloud-ai-platform/azure-core/azure-experiences-and-ecosystems/cme-international-customer-exp/software-localization-onelocbuild/onelocbuild/onboarding/localizationproject for the schema of the manifest file.

Add loc manifest file to define the scope of the new loc process

---

src/common/OneDSLoggerTelemetry/web/client/webExtensionTelemetryEvents.ts
src/web/client/webViews/powerPagesNavigationProvider.ts

This pull request adds enhanced telemetry tracking for the "Open in VS Code Desktop" feature in the Power Pages navigation provider, improving observability for user actions and feature flag status. It introduces new telemetry events, tracks user interactions with dialog options, and ensures feature gating via ECS flags.
**Telemetry enhancements for "Open in Desktop" flow:**
- Added new telemetry event names to the `webExtensionTelemetryEventNames` enum for tracking user actions and dialog interactions related to the "Open in Desktop" feature.
- Updated the `openInDesktop` method in `powerPagesNavigationProvider.ts` to send telemetry events when the feature is clicked, when the ECS feature flag is disabled, when the desktop flow is triggered, and when the desktop URI is successfully …

Add telemetry events for desktop opening actions
