src/client/PortalWebView.ts, src/client/extension.ts, src/common/PortalConfigFinder.ts, src/server/htmlServer.ts, src/server/lib/PortalManifestReader.ts, src/server/yamlServer.ts
Removes limitation on root folder for editing in VSCode
=> Removes limitation on root folder for editing in VSCode

src/client/pac/PacWrapper.ts
[AB#2365285](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2365285)
=> Set interal PAC to use a temp folder for its working directory

src/client/pac/PacWrapper.ts
[AB#2347710](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2347710)
=> Simplify PAC output handling with built-in readline

package.json, src/client/extension.ts, src/client/lib/PacTerminal.ts, src/client/pac/PacWrapper.ts
[AB#2365283](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2365283) add Enable and Disable telemetry commands
=> Adding Telemetry commands

README.md, gulpfile.js, package.json, src/client/extension.ts, src/client/pac/PacWrapper.ts
- Disable Remote/Codespaces installation (#87)
- update to pac CLI 1.8.6 (#89)
- Fixing pathing for case-sensitive OSs (#86)
=> cherry-picking 2 changes to rel/stable

.github/workflows/PullRequest.yml
[AB#2290035](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2290035)
=> Run build and unit tests on MacOS in PR loop

src/client/extension.ts, src/client/lib/PacTerminal.ts, src/client/pac/PacWrapper.ts
[AB#2390883](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2390883)
=> Lazy start the internal PAC process

package.json, src/client/lib/PacActivityBarUI.ts, src/client/pac/PacWrapper.ts, src/client/test/unit/PacWrapper.test.ts
Add pac auth clear to Auth Profiles panel.
[Work item: Auth Panel - pac auth clear](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2396560/)
=> clear auth profiles

package.json
[AB#2448303](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2448303): VS Code Extension: Fix display strings of "Powerplatform" to be "Power Platform"
=> Update config setting category

package.json, package.nls.json
[AB#2451419](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2451419): Localization - extract package.json strings into package.nls.json file
=> Localization - extract package.json strings into package.nls.json file

package.json, package.nls.json, src/client/lib/PacActivityBarUI.ts, src/client/pac/PacWrapper.ts
[AB#2396558](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2396558): Auth Profile Rename command in Auth Panel
=> Add auth profile rename command to the context menu

src/client/snippets/paportal-liquid.code-snippets
Adding code snippets for studio components like different sections, images, videos, buttons, spacer and iframe components. 
Did the sanity check by adding these components in html code of studio pages via pac cli and verified the same from studio.
=> Adding code snippets for studio components

README.md, gulpfile.js
Still waiting for the final pac CLI build
=> pac CLI Nov refresh

.azure-pipelines/OfficialBuild.yml
https://aka.ms/cyberEOSBOM
test build: https://dev.azure.com/dynamicscrm/OneCRM/_build/results?buildId=9137797&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Add SBOM generation task

src/client/snippets/paportal-liquid.code-snippets
Updated description strings for code snippets.
=> Updated description strings for code snippets

loc/translations-export/vscode-powerplatform.xlf, package.json, package.nls.cs.json, package.nls.de.json, package.nls.es.json, package.nls.fr.json, package.nls.it.json, package.nls.ja.json, package.nls.json, package.nls.ko.json, package.nls.pt-BR.json, package.nls.ru.json, package.nls.tr.json, package.nls.zh-CN.json, package.nls.zh-TW.json, src/client/lib/PacActivityBarUI.ts
[AB#2584250](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2584250): Solutions context command - add "copy unique name"
=> Adding `Copy Unique Name` command to the Solution context menu

README.md, gulpfile.js
Updating to PAC v1.11.8 to fix a regression in `pac solution check`
=> Update PAC version

src/client/lib/PacTerminal.ts, src/client/pac/PacWrapper.ts, src/client/telemetry/batchedTelemetryAgent.ts, src/client/test/unit/PacWrapper.test.ts
[AB#2624122](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2624122): Tag PAC executions performed by UI
[AB#2624125](https://dev.azure.com/dynamicscrm/ALM/_workitems/edit/2624125): Tag PAC installed by VS Code
=> Adding telemetry tagging to PAC executions

NOTICE.txt, build/noticeSplitter.js
the noticesplitter.js script is a duplicate from our other repos
=> update 3rd party notice

package-lock.json, package.json
addresses https://github.com/microsoft/powerplatform-vscode/security/dependabot/12
=> address dependabot alert #12 (moment 2.29.2)

gulpfile.js, loc/translations-export/vscode-powerplatform.xlf, package.json, package.nls.json, src/client/lib/PacActivityBarUI.ts, src/client/lib/PanelComponents.ts, src/client/pac/PacWrapper.ts
[AB#2748260](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2748260)
=> Switch Auth Panel to use Universal profiles

README.md, gulpfile.js
- update to latest pac CLI 1.16.5
- PP Activity panel now takes advantage of the new UNIVERSAL auth kind that merges the older ADMIN & DATAVERSE kinds
=> May refresh 1.16.5

src/client/pac/PacWrapper.ts
Cherry-picking the DOTNET_ROLL_FORWARD fix from #220 in release/stable to main
=> Apply Rollforward fix for M1 macs to PAC instance used as UI backend (#220)

src/web/client/common/constants.ts, src/web/client/common/createFileSystem.ts, src/web/client/common/errorHandler.ts, src/web/client/common/localStore.ts, src/web/client/common/remoteFetchProvider.ts
Updating Portal Folder Name for web extension 
Testing:
tested with portal route -
http://localhost:3000/powerplatform/portal/webpages/563a8e53-6cf7-ec11-82e4-000d3a8b4b81?orgUrl=https://org4e297bda.crm10.dynamics.com&dataSource=Dataverse&schema=portalDataverseoldschema&websiteId=24828659-6cf7-ec11-82e4-000d3a8b4b81&websiteName=Site%205&clientSessionId=20d30dc0-040a-11ed-a9c5-d5d08bd7e3e0&Client=PowerPagesStudio
=> Updating Portal Folder Name for web extension

src/web/client/common/remoteFetchProvider.ts
=> added the correct url for logging

.azure-pipelines/OfficialBuild.yml, gulpfile.js, package-lock.json, package.json, src/client/constants.ts, src/client/extension.ts, src/common/telemetry/generated/telemetryConfiguration.ts, src/common/telemetry/telemetryConfigurationDev.ts, src/common/telemetry/telemetryConfigurationProd.ts, src/web/client/extension.ts
[AB#2357997](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2357997): Telemetry - Switch AppInsights key/destination based on build source (offical vs dev)
=> Switch Telemetry key based on Official Build vs Dev

README.md, gulpfile.js
cherry-pick of #252 (29290e6)
Co-authored-by: davidjen@DAVIDJEN-DEV <davidjen@microsoft.com>
=> [main] July refresh: pac CLI 1.17.x (#252)

README.md, gulpfile.js
=> fix paportal download errors

README.md, gulpfile.js
cherry-pick of #259
fixes #255
Co-authored-by: david@DAVID-PC <davidjen@microsoft.com>
=> fix paportal download errors (issue 255)

src/client/lib/PacTerminal.ts
[AB#2869601](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2869601) Remove unused LauncherAgent
=> Removing LauncherAgent

src/web/client/common/authenticationProvider.ts, src/web/client/common/constants.ts, src/web/client/common/portalSchema.ts, src/web/client/common/remoteFetchProvider.ts, src/web/client/common/remoteSaveProvider.ts, src/web/client/utility/CommonUtility.ts, src/web/client/utility/UrlBuilder.ts
- This change addressed loading and saving of custom css files that are saved as Dataverse entityType Annotations.
- Improvements to common utility functions.
=> Custom css file edit enable

src/web/client/common/remoteFetchProvider.ts, src/web/client/common/remoteSaveProvider.ts
Added a filter to check for genuine save events.
=> Bug fix for save error popup.

gulpfile.js, loc/translations-export/vscode-powerplatform.xlf, src/web/client/common/authenticationProvider.ts, src/web/client/common/errorHandler.ts, src/web/client/common/localStore.ts, src/web/client/common/remoteFetchProvider.ts, src/web/client/common/remoteSaveProvider.ts, src/web/client/extension.ts
To address string literal issue changes are made directly - link to issue - https://github.com/Microsoft/vscode-nls-dev/issues/5
Testing:
tested with portal route -
http://localhost:3000/powerplatform/portal/webpages/563a8e53-6cf7-ec11-82e4-000d3a8b4b81?orgUrl=https://org4e297bda.crm10.dynamics.com&dataSource=Dataverse&schema=portalDataverseoldschema&websiteId=24828659-6cf7-ec11-82e4-000d3a8b4b81&websiteName=Site%205&clientSessionId=20d30dc0-040a-11ed-a9c5-d5d08bd7e3e0&Client=PowerPagesStudio
=> Localization changes for web extension

loc/translations-export/vscode-powerplatform.xlf, src/client/lib/PanelComponents.ts
Adding Cloud Instance and Resource info to the Auth Profile tooltip
=> AuthProfile tooltip should have Cloud and Resource info

NOTICE.txt
updated from latest official build
https://dev.azure.com/dynamicscrm/OneCRM/_componentGovernance/173111?_a=components&typeId=5542069&alerts-view-option=active
The CompGovernance's raw output is unsorted, using this script to sort and cleanup:
build/noticeSplitter.js
=> update 3rd party notices

README.md, gulpfile.js
addresses #294 
[AB#2959078](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/2959078)
=> Sept refresh QFE

.github/workflows/PullRequest.yml, src/web/client/common/fileSystemProvider.ts, src/web/client/common/localStore.ts
Cherry-pick of PR #346
AB#3025834
=> [rel/stable] cherry pick 3025834 - Revert access token change - no silent prompts

README.md, gulpfile.js
needs to also be cherry-picked into rel/stable
=> [main] pick up latest pac CLI 1.20.3 with paportal list fix

src/web/client/dal/remoteFetchProvider.ts, src/web/client/dal/remoteSaveProvider.ts, src/web/client/schema/portalSchemaInterface.ts, src/web/client/telemetry/webExtensionTelemetry.ts
=> 3076077: Save file telemetry - introduce file extension type

src/web/client/common/constants.ts, src/web/client/extension.ts, src/web/client/telemetry/webExtensionTelemetry.ts
=> Fix init params log telemetry

README.md, gulpfile.js
* Bump decode-uri-component from 0.2.0 to 0.2.2 (#379)
* [rel/stable] Nov refresh
Cherry-pick of PR #377 from release/stable
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: david@DAVID-PC <davidjen@microsoft.com>
[AB#3077859](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3077859)
=> [main] pac CLI Nov refresh

loc/translations-export/vscode-powerplatform.xlf, package.json, src/client/extension.ts, src/client/powerpages/Contentsnippet.ts, src/client/powerpages/utils/CommonUtils.ts
- Gives a quick pick to select name and type
- Runs content snippet yeoman generator
=> Integrated content snippet in vscode

src/web/client/WebExtensionContext.ts, src/web/client/context/entityData.ts, src/web/client/context/entityDataMap.ts, src/web/client/context/fileData.ts, src/web/client/context/fileDataMap.ts, src/web/client/dal/fileSystemProvider.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/dal/remoteSaveProvider.ts, src/web/client/extension.ts, src/web/client/test/integration/urlBuilderUtil.test.ts, src/web/client/utilities/schemaHelperUtil.ts, src/web/client/utilities/urlBuilderUtil.ts
writeCall check for save file contents back to dataverse conditional check is now maintained based on dirty changes present in VFS - contrary to previous weak check
Also, introduced proper getter/setter for better code readability for fileData, entityData and Webcontext classes
=> 3131631 - Fix fileSystemProvider writeFile call concurrency issue

package.json, src/client/constants.ts, src/client/extension.ts
=> Add feature flag to control create, delete and rename code flow

src/common/telemetry/telemetryConfigurationDev.ts, src/common/telemetry/telemetryConfigurationProd.ts, src/web/client/telemetry/webExtensionTelemetry.ts
=> [rel/stable] Fix web ext telemetry imports

src/client/power-pages/commonUtility.ts, src/client/power-pages/constants.ts, src/client/power-pages/fileSystemCallbacks.ts
TODO - Need to take care of some notification that pop-up due to diagnostics running on a deleted files.
=> Delete action support for all other entities

src/client/power-pages/commonUtility.ts, src/client/power-pages/constants.ts, src/client/power-pages/fileSystemCallbacks.ts, src/client/power-pages/fileSystemUpdatesUtility.ts, src/client/power-pages/validationDiagnostics.ts
Update: Fixed the issues in page-template, and polls entity adx_name updates
TODO: Need to add telemetry and localization updates
Verify yml file field updates for each entity
=> Rename action support for power pages entities

.azure-pipelines/OfficialBuild.yml, .github/workflows/PullRequest.yml, CONTRIBUTING.md
Task [AB#3017488](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3017488): VS Code - Update Node to LTS 18?
=> Update to Node LTS 18

src/client/power-pages/commonUtility.ts, src/client/power-pages/constants.ts, src/client/power-pages/fileSystemUpdatesUtility.ts
Updated the YAML param based on file entity type instead of generic adx_name to the required param for each entity.
=> Update correct YAML file params for entities

src/client/snippets/paportal-liquid.code-snippets, src/server/constants/AutoComplete.ts, src/server/lib/LiquidAutoCompleteRule.ts
Added auto-complete support for more portal objects, their attributes n template tags.
=> Autocomplete support for portal objects, attributes & template tags

package.json, src/client/constants.ts, src/client/extension.ts
Removing the previously added feature flag as the feature is stabilized
=> Remove CRUD operations feature flag

src/client/power-pages/create/CreateOperationConstants.ts, src/client/power-pages/create/Webfile.ts, src/client/power-pages/create/utils/CommonUtils.ts
- Added handling of existing webfiles
- Added a generic method for error handling
=> [Powerpages][Create] Duplicate webfile handling

.github/workflows/PullRequest.yml, .github/workflows/Snapshot.yml, README.md, gulpfile.js, package-lock.json, package.json, src/debugger/test/runTest.ts
=> PAC update to 1.22.3

l10n/bundle.l10n.cs.json, l10n/bundle.l10n.de.json, l10n/bundle.l10n.es.json, l10n/bundle.l10n.fr.json, l10n/bundle.l10n.it.json, l10n/bundle.l10n.ja.json, l10n/bundle.l10n.ko.json, l10n/bundle.l10n.pt-br.json, l10n/bundle.l10n.ru.json, l10n/bundle.l10n.tr.json, l10n/bundle.l10n.zh-cn.json, l10n/bundle.l10n.zh-tw.json, loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf, package/.gitignore
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230424-181701-mqge8yftf]

package.json, src/client/extension.ts, src/client/power-pages/bootstrapdiff/BootstrapDiff.ts
Creating a new command 'BootstrapDiff' to highlight the changes made by the pac cli command bootstrap-migrate
=> Creating a new command 'BootstrapDiff'

README.md, gulpfile.js, l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf
=> April Refresh

l10n/bundle.l10n.cs.json, l10n/bundle.l10n.de.json, l10n/bundle.l10n.fr.json, l10n/bundle.l10n.it.json, l10n/bundle.l10n.ko.json, l10n/bundle.l10n.ru.json, l10n/bundle.l10n.tr.json, l10n/bundle.l10n.zh-cn.json, loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230523-175516-vxbg1excn2]

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf, package.nls.cs.json, package.nls.de.json, package.nls.es.json, package.nls.fr.json, package.nls.it.json, package.nls.ja.json, package.nls.ko.json, package.nls.pt-br.json, package.nls.ru.json, package.nls.tr.json, package.nls.zh-cn.json, package.nls.zh-tw.json
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230602-032843-ph3rt29854]

l10n/bundle.l10n.json, src/web/client/common/constants.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/schema/constants.ts, src/web/client/schema/portalSchema.ts, src/web/client/telemetry/constants.ts, src/web/client/utilities/commonUtil.ts, src/web/client/utilities/folderHelperUtility.ts, src/web/client/utilities/schemaHelperUtil.ts, src/web/client/utilities/urlBuilderUtil.ts
=> Fetch support - List, Basic forms and Advanced forms - old and new data model

package-lock.json, package.json, src/web/client/common/constants.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/extension.ts, src/web/client/test/integration/commonUtil.test.ts, src/web/client/utilities/commonUtil.ts, webpack.config.js
=> Support media file preview and fix no content error on empty payload return

package-lock.json, package.json, src/client/extension.ts, src/common/copilot/PowerPagesCopilot.ts
- Added config for copilot view
- Added html skeleton for copilot
- FCB to enable/disable webview
=> ProDev Copilot Infra and Conditional rendering of view

src/web/client/dal/fileSystemProvider.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/schema/constants.ts, src/web/client/utilities/commonUtil.ts, src/web/client/utilities/fileAndEntityUtil.ts, src/web/client/utilities/folderHelperUtility.ts, src/web/client/utilities/urlBuilderUtil.ts
Fixed an issue with loading new data model media files on lazy load
=> Load V2 model media files on readfile flow

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, package.nls.cs.json, package.nls.de.json, package.nls.es.json, package.nls.fr.json, package.nls.it.json, package.nls.ko.json, package.nls.pt-br.json, package.nls.ru.json, package.nls.tr.json, package.nls.zh-cn.json, package.nls.zh-tw.json, src/client/extension.ts, src/common/copilot/IntelligenceApiService.ts, src/common/copilot/PowerPagesCopilot.ts
- Copilot notification to powerpages users.
- Localization changes
=> [Powerpages][copilot] Try copilot notification

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, src/client/lib/EnvAndSolutionTreeView.ts, src/client/pac/PacTypes.ts
Add visual indicator to Managed solutions, and add tooltip relaying Managed/Unmanaged state
#199 
[AB#3492656](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3492656)
=> Solution Panel - Add Icon and Tooltip to display Managed/Unmanaged

src/common/Utils.ts, src/common/copilot/PowerPagesCopilot.ts, src/common/copilot/constants.ts
=> [Powerpages][Copilot]Auth Profile Progress notification

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230720-185657-zcafcy54]

src/common/copilot/assets/scripts/copilot.js, src/common/copilot/assets/styles/copilot.css
- Disabling onclick until current response is completed
- Scroll to latest message.
=> suggestion prompt, on click fix and scroll fix

src/web/client/WebExtensionContext.ts, src/web/client/common/authenticationProvider.ts, src/web/client/common/errorHandler.ts, src/web/client/dal/concurrencyHandler.ts, src/web/client/dal/fileSystemProvider.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/dal/remoteSaveProvider.ts, src/web/client/extension.ts, src/web/client/services/NPSService.ts, src/web/client/services/etagHandlerService.ts, src/web/client/telemetry/webExtensionTelemetry.ts, src/web/client/telemetry/webExtensionTelemetryInterface.ts, src/web/client/test/integration/WebExtensionContext.test.ts, src/web/client/test/integration/errorHandler.test.ts, src/web/client/test/integration/webExtensionTelemetry.test.ts, src/web/client/utilities/commonUtil.ts, src/web/client/webViews/NPSWebView.ts
Added Method Name in sendErrorTelemetry API
=> Added Method Name in sendErrorTelemetry API

src/client/power-pages/create/Contentsnippet.ts, src/client/power-pages/create/CreateCommandWrapper.ts, src/client/power-pages/create/PageTemplate.ts, src/client/power-pages/create/WebTemplate.ts, src/client/power-pages/create/Webfile.ts, src/client/power-pages/create/Webpage.ts, src/client/power-pages/create/utils/CommonUtils.ts, src/client/power-pages/fileSystemCallbacks.ts, src/client/power-pages/fileSystemUpdatesUtility.ts, src/client/power-pages/telemetry.ts, src/client/power-pages/validationDiagnostics.ts
Added method Name in telemetry for Desktop extension
=> Added method Name in telemetry for Desktop extension

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230731-182844-msn7hzxzh5]

src/common/copilot/assets/walkthrough/Copilot-In-PowerPages.md, src/common/copilot/dataverseMetadata.ts
- Updated Regex for matching required YML file
- Updated feature walkthrough: Webtemplate for webApi and arrow keys enhancement.
=> [PowerPages Copilot][Dataverse Integration] Updated Regex for matching file

src/common/copilot/assets/scripts/copilot.js
- Disabling Input while response is in progress
=> [Powerpages Copilot] Disabling Input while response is in progress

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, src/common/copilot/IntelligenceApiService.ts, src/common/copilot/dataverseMetadata.ts, src/common/copilot/telemetry/ITelemetry.ts, src/common/copilot/telemetry/copilotTelemetry.ts, src/common/copilot/telemetry/telemetryConstants.ts, src/common/copilot/user-feedback/CESSurvey.ts, src/web/client/common/authenticationProvider.ts
- Updated telemetry event names
- Updated type for error telemetry
=> [Powerpages Copilot] Telemetry event name fix

src/common/copilot/assets/walkthrough/Copilot-In-PowerPages.md
- Update walkthrough to reflect classification changes.
=> [Powerpages Copilot] Updated walkthrough

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230821-121818-4r9e33c445]

l10n/bundle.l10n.cs.json, l10n/bundle.l10n.es.json, l10n/bundle.l10n.ja.json, l10n/bundle.l10n.ko.json, l10n/bundle.l10n.pt-br.json, l10n/bundle.l10n.ru.json, l10n/bundle.l10n.zh-cn.json, l10n/bundle.l10n.zh-tw.json
localized strings from the latest translated .xlf drop in #676
=> Extracted localization from #676

loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.tr.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20230823-000142-hq18mzqap6]

src/web/client/dal/remoteFetchProvider.ts, src/web/client/schema/portalSchema.ts, src/web/client/utilities/urlBuilderUtil.ts
Cherry picked: Mimetype regression fix for old data model webfiles save scenario - https://github.com/microsoft/powerplatform-vscode/pull/685 
and In case of multiple annotations/attachments associated with a webfile pick the latest modified by the user - https://github.com/microsoft/powerplatform-vscode/pull/687
=> Webfile fix for old data model file load 

README.md
=> Release notes for QFE - cherry-pick to main

src/web/client/context/userDataMap.ts
containerId: string -> id of FRS container
fileName: string -> name of current active file
filePath: string -> path of current active file
userName: string -> name of user
userId: string -> user id
=> userDataMap intreface for co-presence audience

src/common/copilot/PowerPagesCopilot.ts
=> Show "Preview" text in copilot webview

README.md, gulpfile.mjs, l10n/bundle.l10n.de.json, l10n/bundle.l10n.fr.json, l10n/bundle.l10n.it.json, l10n/bundle.l10n.json, l10n/bundle.l10n.tr.json
Cherry-pick of #704 to release
=> [rel/stable cherry-pick] August Refresh (#704)

l10n/bundle.l10n.fr.json, l10n/bundle.l10n.ja.json, l10n/bundle.l10n.ko.json, l10n/bundle.l10n.ru.json, l10n/bundle.l10n.zh-cn.json, l10n/bundle.l10n.zh-tw.json, loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20231016-155628-tpz1qq1h02]

README.md, gulpfile.mjs
[AB#3646160](https://dev.azure.com/dynamicscrm/1fb98997-2f9e-4734-be8a-9728680447c2/_workitems/edit/3646160) fixing bad version of PAC which breaks output
=> Bump PAC and extension version

.azure-pipelines/OfficialBuild.yml, src/common/copilot/assets/copilotStrings.ts, src/common/copilot/assets/scripts/copilot.js, src/common/copilot/welcome-notification/CopilotNotificationPanel.ts
Added localization for copilot and notification panel.
=> Localization for copilot webview strings

README.md, gulpfile.mjs, l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf
Release Notes, and update PAC to 1.29.x
=> Release Notes and PAC update

README.md, gulpfile.mjs
=> [rel/stable cherry-pick] PAC update to v1.29.10

README.md, gulpfile.mjs
Cherry pick of #786 to release/stable
=> [rel/stable cherry-pick] PAC update to v1.29.11

.vscode/settings.json, l10n/bundle.l10n.json, src/web/client/WebExtensionContext.ts, src/web/client/test/integration/WebExtensionContext.test.ts, src/web/client/utilities/urlBuilderUtil.ts
Fixing web extension test cases with updated code flows.
=> Fix Web extension context integration test cases

src/common/OneDSLoggerTelemetry/IEventTypes.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts
Populate ContextInfo, TenantId and ObjectId attributes for Vscode Web
=> Populate ContextInfo, TenantId and ObjectId attributes for Vscode Web

src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts
Exposing oneDsLoggerWrapper to get reinitialized with different iKey
=> Exposing oneDsLoggerWrapper to get reinitialized with different iKey

src/web/client/common/worker/webworker.js
Fixed bug for the "valueChanged" event listener on tab change to update selection dictionary in sharedmap for FRS. Hence broadcasting recent location of a user to everyone in the sharedmap container.
=> Bug fixed "valueChanged" event listener to update sharedmap

CHANGELOG.md, gulpfile.mjs, src/client/lib/AuthPanelView.ts, src/client/pac/PacTypes.ts, src/client/test/unit/PacWrapper.test.ts
Bump PAC version, and update PacTypes + AuthProfile UI to match the PAC changes
=> Auth Profile listing fix

CHANGELOG.md, gulpfile.mjs, src/client/lib/AuthPanelView.ts, src/client/pac/PacTypes.ts, src/client/test/unit/PacWrapper.test.ts
Cherry-pick to release #841 
Bump PAC version, and update PacTypes + AuthProfile UI to match the PAC changes
=> [release/stable cherry-pick] Auth Profile listing fix

src/web/client/common/constants.ts, src/web/client/dal/fileSystemProvider.ts, src/web/client/telemetry/constants.ts
In this PR I added telemetry log for rename and delete operations, in order to get number of users using these functionalities..
=> Adding Error Telemetry for Rename and Delete Operations

.github/CODEOWNERS, src/common/OneDSLoggerTelemetry/telemetryConstants.ts, src/web/client/extension.ts
For unauthenticated scenario flow the data in US geo
=> For unauthenticated scenario flow the data in US geo

package.json, src/web/client/utilities/commonUtil.ts
Update package.json and commonUtil.ts
=> Enabling Copresence in Vscode for web

src/common/OneDSLoggerTelemetry/oneDSLogger.ts, src/web/client/common/constants.ts, src/web/client/extension.ts
We are determining org geo using Artemis service. Artemis service gives us the org geo based on orgId and use the same geo for data residency
=> Handle orgGeo params for telemetry data residency

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20240221-043145-n10pv0zrt]

package-lock.json, package.json, src/client/extension.ts, src/client/telemetry/TelemetryEventNames.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts, src/common/copilot/IntelligenceApiService.ts, src/common/copilot/PowerPagesCopilot.ts, src/common/copilot/assets/scripts/copilot.js, src/common/copilot/constants.ts, src/common/copilot/dataverseMetadata.ts, src/common/copilot/user-feedback/CESSurvey.ts, src/common/copilot/welcome-notification/CopilotNotificationPanel.ts
This pull request includes major changes in the codebase, primarily focusing on the modification and addition of new functionalities in the telemetry and logging, user feedback handling, and API request handling. The most significant changes include:
1. Addition of new dependencies in the `package.json` file.
2. Modification of the telemetry and logging functionalities.
3. Changes in the user feedback handling.
4. Updates in the API request handling.
5. Changes in the constants used across different files.
Here are the most important changes in detail:
New Dependencies:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R1025-R1026): Added new dependencies `@microsoft/1ds-core-js` and `@microsoft/1ds-post-js`, and moved some existing …
=> Merge Main to release/stable 

src/common/OneDSLoggerTelemetry/IEventTypes.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts
Added orgGeo and fix errorName
=> Added orgGeo and fix errorName

src/web/client/common/worker/webworker.js, src/web/client/extension.ts, src/web/client/utilities/fileAndEntityUtil.ts, src/web/client/webViews/QuickPickProvider.ts
Reverts microsoft/powerplatform-vscode#872
=> Revert "[Bug Fix] Populating SharedWorkSpace Container for Initial File Load"

src/web/client/common/worker/webworker.js, src/web/client/extension.ts, src/web/client/utilities/collaborationUtils.ts, src/web/client/utilities/fileAndEntityUtil.ts, src/web/client/webViews/QuickPickProvider.ts
This pull request primarily focuses on improving the `loadContainer` function in the `webworker.js` file and refining the handling of entity information in the `extension.ts` file. The changes in `webworker.js` include fixing a typo in a variable name, adding a new function, and adjusting the logic to handle initial state. In `extension.ts`, the changes involve better management of active text editor changes, workspace state changes, and the creation of a web worker instance.
Changes to `webworker.js`:
* [`src/web/client/common/worker/webworker.js`](diffhunk://#diff-8e0adceeebffaef7b18326a30ca124d6e2d8448e6732876fdf21ee42b14897c1L81-R81): Corrected a typo in a variable name from `intital` to `initial` and changed its initial value to `true`.
* …
=> [Bug Fix] Populating SharedWorkSpace Container for Initial File Load

src/common/OneDSLoggerTelemetry/IEventTypes.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts, src/web/client/common/constants.ts, src/web/client/telemetry/webExtensionTelemetry.ts, src/web/client/telemetry/webExtensionTelemetryInterface.ts, src/web/client/test/integration/webExtensionTelemetry.test.ts
This pull request refactors the OneDSLoggerTelemetry class to include SKU information in the telemetry data. This allows for better tracking and analysis of the SKU usage.
=> Refactor OneDSLoggerTelemetry to include SKU information

src/common/OneDSLoggerTelemetry/IEventTypes.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts, src/web/client/extension.ts, src/web/client/telemetry/constants.ts
Adding OrgGeo as a Root Attribute (Ask from Saranya)
=> Adding OrgGeo as a Root Attribute (Ask from Saranya)

src/web/client/assets/previewSite.svg, src/web/client/webViews/powerPagesNavigationProvider.ts
=> Update SVG file names and titles for Power Pages navigation

CHANGELOG.md
This pull request includes updates to the `CHANGELOG.md` file. The changes reflect the new version of the Power Platform Extension, which is now 2.0.41. The updates include the addition of text search functionality, improved accuracy for Copilot prompt responses in Forms scenarios, and the availability of Copilot in the United Kingdom, Europe, and Australia. Furthermore, the version of pac CLI has been updated to 1.31.6.
=> February refresh release notes

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20240325-232926-kzpxq7bdv2]

package.json, src/web/client/WebExtensionContext.ts, src/web/client/common/worker/webworker.js, src/web/client/extension.ts, src/web/client/utilities/commonUtil.ts, src/web/client/webViews/QuickPickProvider.ts, src/web/client/webViews/userCollaborationProvider.ts
This pull request includes the following changes:
- Hiding my current connect from treeview and quickpick
- Enable co-presence on vscode web
=> Hiding my current presence from quickpick and treeview

src/web/client/extension.ts, src/web/client/utilities/fileAndEntityUtil.ts, src/web/client/webViews/QuickPickProvider.ts
Bug Fixes in this PR: 
1. Co-Presence was not triggering for non-localized content (i.e. entities other than webpage), this PR addresses the issue and fixes the same.
2. If no other user is present on the page: People on this site should be 0
=> [Bug Fix] Co-Presence for non-localized content

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, package.json, package.nls.json, src/common/copilot/PowerPagesCopilot.ts
The code changes update the Copilot panel title and clear conversation button text to use localized strings. This improves the user experience by providing clear and localized labels for these elements.
=> feat: Update Copilot panel title and clear conversation button

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20240506-225230-3ss12jy8v1]

src/common/copilot/PowerPagesCopilot.ts, src/common/utilities/Utils.ts
This pull request primarily focuses on improving the availability check for the Copilot feature in the PowerPages application. The most significant changes include the addition of a new function `checkCopilotAvailability`, and the refactoring of the `PowerPagesCopilot` class to use this new function. 
Changes to improve Copilot availability check:
* [`src/common/utilities/Utils.ts`](diffhunk://#diff-bf8425ddaf7889e68044eb87abc71b32754d10ce9a306723063cf231b01f590cR186-R207): A new function `checkCopilotAvailability` has been added. This function checks the availability of the Copilot feature based on the `aibEndpoint` value, the organization ID (`orgID`), and the tenant ID (`tenantId`). It sends telemetry events when the Copilot feature is unavailable.
Refactoring of the …
=> [PowerPages][Copilot] Copilot Availability Check Util

loc/translations-import/vscode-powerplatform.cs.xlf, loc/translations-import/vscode-powerplatform.de.xlf, loc/translations-import/vscode-powerplatform.es.xlf, loc/translations-import/vscode-powerplatform.fr.xlf, loc/translations-import/vscode-powerplatform.it.xlf, loc/translations-import/vscode-powerplatform.ja.xlf, loc/translations-import/vscode-powerplatform.ko.xlf, loc/translations-import/vscode-powerplatform.pt-BR.xlf, loc/translations-import/vscode-powerplatform.ru.xlf, loc/translations-import/vscode-powerplatform.tr.xlf, loc/translations-import/vscode-powerplatform.zh-CN.xlf, loc/translations-import/vscode-powerplatform.zh-TW.xlf
=> powerplatform-vscode Localization hand-back [CTAS - RunID=20240628-001241-eh7t5xpfc4]

gulpfile.mjs
Updating to latest PAC release
=> Update to PAC 1.33.5

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts, src/common/constants.ts, src/common/copilot/IntelligenceApiService.ts, src/common/copilot/PowerPagesCopilot.ts, src/common/copilot/constants.ts
This pull request adds the `apiRequest` object to the codebase. It includes changes to multiple files and introduces new interfaces such as `UserPrompt` and `IApiRequestParams`. The `sendApiRequest` function has been updated to accept the `apiRequest` object as a parameter. This change improves the code structure and prepares the codebase for future enhancements related to API requests.
=> [PowerPages Copilo] Add apiRequest as object

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, src/common/ErrorConstants.ts, src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts, src/common/chat-participants/powerpages/PowerPagesChatParticipantConstants.ts, src/common/chat-participants/powerpages/PowerPagesChatParticipantUtils.ts, src/common/utilities/OrgHandlerUtils.ts
This pull request includes several changes focused on improving authentication handling, enhancing user prompts, and organizing utility functions. The most important changes include adding new error constants, updating the `PowerPagesChatParticipant` class to handle authentication more effectively, and introducing a new utility function for cleaning user prompts.
* [`src/common/ErrorConstants.ts`](diffhunk://#diff-9c229dd84e04c3863ba4eeb8d0c00b0a64c6a6665af835432906266ac10b69e4L54-R55): Added a new error constant `PAC_AUTH_FAILED` for PAC authentication failures.
* [`src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts`](diffhunk://#diff-885f58fd5bd7ee590ddae0f7854d056026aff9b576864e07f61887fb7586da29L15-R17): Updated the `PowerPagesChatParticipant` class to check for …
=> [@powerpages] Chat Variable and Org Handling

src/common/copilot/PowerPagesCopilot.ts, src/common/copilot/telemetry/telemetryConstants.ts, src/common/copilot/welcome-notification/CopilotNotificationPanel.ts
This pull request includes several changes to enhance telemetry tracking and improve the user experience when interacting with GitHub Copilot in the PowerPages extension. The most important changes include adding new telemetry events, updating existing telemetry calls, and refining command executions.
* [`src/common/copilot/telemetry/telemetryConstants.ts`](diffhunk://#diff-8be6094fdbb66269472fff9fba0b0fa6042e180ee442d1d0dc9d2cc9320413b9R40-R42): Added new telemetry events `CopilotNotificationTryGitHubCopilotClicked` and `CopilotPanelTryGitHubCopilotClicked`.
* [`src/common/copilot/PowerPagesCopilot.ts`](diffhunk://#diff-98c063ddf20a69c9594332e9f968fe00b2e009c5de85256f9e336c089e6880abL18-R18): Updated imports to include the new telemetry event `CopilotPanelTryGitHubCopilotClicked`.
* …
=> Telemetry constants and add GitHub Copilot Launch event

CHANGELOG.md
This pull request updates the `CHANGELOG.md` file to reflect the latest changes and bug fixes in the Power Platform Extension. The most important changes include updating the version number, adding new CLI release details, and documenting recent bug fixes.
Updates to version and CLI release:
* Updated version number to `2.0.74` and added details for `pac CLI 1.35.1` (September 2024 refresh). (`CHANGELOG.md`)
Bug fixes:
* Documented the fix for the "Not yet available in your region" issue in Copilot for Power Pages. (`CHANGELOG.md`)
* Documented the fix for the Power Pages generator installation issue. (`CHANGELOG.md`)
=> October release notes

CHANGELOG.md
This pull request updates the CHANGELOG.md file to reflect the latest changes in the Power Platform Extension.
Updates to version and CLI release:
- Updated version number to 2.0.76 and added details for PAC CLI 1.37.4 (November 2024 refresh). (CHANGELOG.md)
=> December Release Notes

.vscode/tasks.json
To be able to easily run tests from VS Code, added test scripts in `tasks.json`
=> Add test scripts in .vscode\tasks.json

src/common/OneDSLoggerTelemetry/IEventTypes.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts
Added  orgGeo in a separate column
=> Added  orgGeo in a separate column

src/common/copilot/welcome-notification/copilotNotification.css
This PR contains changes that improves the accessibility of the extension:
- [copilotNotification.css](https://github.com/microsoft/powerplatform-vscode/compare/users/ssatheesh/resolve_a11y_issues?expand=1#diff-2b8e93828d4b89d36a36133141a1c7cbcaf849f4cecc56d1a36c482ea3d4668dR88): contains the necessary css changes to show a focus ring around the checkbox container (checkbox + label)
=> Enhance Accessibility

CHANGELOG.md
This pull request updates the CHANGELOG.md file to reflect the latest changes in the Power Platform Extension.
- Updated version number to 2.0.78.
- Updated the latest PAC CLI version.
- Added information on the bug fixes and enhancements made.
=> Add Release Notes for January Release

src/client/extension.ts, src/client/power-pages/preview-site/PreviewSite.ts, src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts, src/common/chat-participants/powerpages/PowerPagesChatParticipantUtils.ts, src/common/chat-participants/powerpages/commands/create-site/CreateSiteHelper.ts, src/common/constants.ts, src/common/copilot/IntelligenceApiService.ts, src/common/copilot/PowerPagesCopilot.ts, src/common/copilot/dataverseMetadata.ts, src/common/copilot/telemetry/copilotTelemetry.ts, src/common/copilot/user-feedback/CESSurvey.ts, src/common/services/ArtemisService.ts, src/common/services/AuthenticationProvider.ts, src/common/services/BAPService.ts, src/common/services/PPAPIService.ts, src/common/utilities/Utils.ts, src/web/client/WebExtensionContext.ts, src/web/client/extension.ts, src/web/client/services/NPSService.ts, src/web/client/services/graphClientService.ts, src/web/client/test/integration/AuthenticationProvider.test.ts, src/web/client/test/integration/WebExtensionContext.test.ts
Eliminate the ITelemetry parameter from various functions to streamline telemetry handling and improve code clarity. This change enhances the overall structure without altering the telemetry functionality.
=> Refactor telemetry handling by removing ITelemetry parameter from functions

src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts, src/client/power-pages/actions-hub/models/IWebsiteInfo.ts, src/client/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.ts, src/client/power-pages/actions-hub/tree-items/InactiveGroupTreeItem.ts, src/client/power-pages/preview-site/PreviewSite.ts, src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts, src/client/test/Integration/power-pages/actions-hub/ActionsHubTreeDataProvider.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/EnvironmentGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/InactiveGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/SiteTreeItem.test.ts, src/common/services/Interfaces.ts, src/common/services/PPAPIService.ts, src/common/utilities/WebsiteUtil.ts, src/web/client/utilities/commonUtil.ts
This pull request includes several changes to the `power-pages` module, focusing on standardizing naming conventions, adding a new property to the `IWebsiteInfo` interface, and updating tests accordingly.
* Updated variable names in `fetchWebsites` to use camelCase (`websiteRecordId`, `websiteUrl`) in `ActionsHubCommandHandlers.ts`.
* Standardized property names in `ActiveGroupTreeItem` and `InactiveGroupTreeItem` to camelCase (`websiteRecordId`, `websiteUrl`) [[1]](diffhunk://#diff-6607677aded2f34ed6d7c10db4c12dbf9e2181f9184881317d737865fe322985L37-R43) [[2]](diffhunk://#diff-f095a51fbaf8fbca117254e89bc433d1281f9018fd0e5d185c97e3d79007f91eL36-R42).
* Updated the `PreviewSite` class to use camelCase for `websiteUrl`.
* Added `siteVisibility` property to `IWebsiteInfo` interface in …
=> [Power Pages] Refactor website details to use camelCase properties

l10n/bundle.l10n.json, serve.json, src/common/copilot/user-feedback/CESSurvey.ts
Add a title attribute to the Submit button in the Copilot feedback form for improved accessibility and user experience. Additionally, ensure consistency in the localization strings and update the site management URL message.
=> Add title attribute to Copilot feedback Submit button

.vscode/settings.json, src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts, src/client/power-pages/actions-hub/Constants.ts, src/client/power-pages/actions-hub/models/IWebsiteInfo.ts, src/client/power-pages/actions-hub/models/SiteVisibility.ts, src/client/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.ts, src/client/power-pages/actions-hub/tree-items/InactiveGroupTreeItem.ts, src/client/power-pages/actions-hub/tree-items/OtherSitesGroupTreeItem.ts, src/client/power-pages/preview-site/PreviewSite.ts, src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/ActiveGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/EnvironmentGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/InactiveGroupTreeItem.test.ts, src/client/test/Integration/power-pages/actions-hub/tree-items/SiteTreeItem.test.ts, src/common/services/Interfaces.ts, src/common/utilities/WebsiteUtil.ts
- ✨ Added new properties `createdOn` and `creator` to website details.
- 🔄 Refactored site visibility handling to use an enum.
- 🛠️ Updated various components to utilize new properties.
- ✅ Enhanced tests to cover new functionality.
=> [Power Pages][Actions Hub] Enhance site details feature

.github/copilot-instructions.md
This commit introduces a comprehensive set of coding and test instructions for Copilot to use.
- 📜 Added coding guidelines including naming conventions and style rules.
- 🧪 Included test instructions for writing and running tests effectively.
=> Add copilot instructions file

gulpfile.mjs
=> Bump CLI version to 1.40.4

l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, src/client/power-pages/preview-site/Constants.ts, src/client/power-pages/preview-site/PreviewSite.ts
- ✨ Added a new message for the preview indicating that it shows published changes.
- 🔧 Updated localization files to include the new message.
- 📜 Modified the Constants and PreviewSite files to utilize the new message.
=> [Power Pages][Preview] Add preview message for published changes

.vscode/settings.json, package.json
- ✏️ Added additional words to the cSpell configuration.
- 🗑️ Removed unused activation events from package.json.
=> Enhance spell check words and clean activation events

gulpfile.mjs
=> Bump PAC version to 1.41.1

package.json
This pull request includes updates to the `package.json` file to enhance the categorization and description of the package. The most important changes include adding new categories and keywords, and expanding the description for the `powerpages` package.
The changes will help in showing up our extension in this list `Install Chat Extensions...`
Enhancements to categorization and keywords:
* Added new categories: "Chat" and "AI" to the `categories` array.
* Added new keywords: "Power Pages", "Power Apps", "copilot", and "chat" to the `keywords` array.
Enhancements to package description:
* Expanded the description for the `powerpages` package by adding a `disambiguation` field with detailed information and examples for the Copilot chat experience.
`disambiguation` property helps in …
=> Enhance package.json by adding new categories and keywords for improved discoverability and updating Copilot description for Power Pages

.vscode/settings.json, CHANGELOG.md, gulpfile.mjs, l10n/bundle.l10n.json, loc/translations-export/vscode-powerplatform.xlf, package-lock.json, package.json, package.nls.json, src/client/PortalWebView.ts, src/client/extension.ts, src/client/lib/AuthPanelView.ts, src/client/power-pages/actions-hub/ActionsHub.ts, src/client/power-pages/actions-hub/ActionsHubCommandHandlers.ts, src/client/power-pages/actions-hub/ActionsHubTreeDataProvider.ts, src/client/power-pages/actions-hub/Constants.ts, src/client/power-pages/actions-hub/TelemetryHelper.ts, src/client/test/Integration/power-pages/actions-hub/ActionsHub.test.ts, src/client/test/Integration/power-pages/actions-hub/ActionsHubCommandHandlers.test.ts, src/client/test/Integration/power-pages/actions-hub/TelemetryHelper.test.ts, src/common/OneDSLoggerTelemetry/oneDSLogger.ts, src/common/copilot/user-feedback/feedback.css, src/common/ecs-features/ecsFeatureGates.ts, src/common/services/Interfaces.ts, src/web/client/common/constants.ts, src/web/client/dal/fileSystemProvider.ts
This PR contains the latest changes from master.
=> Merge commits from main

gulpfile.mjs
=> Bump PAC version to 1.43.6

package-lock.json, package.json
This PR bumps some vulnerable packages to their latest versions to address security vulnerabilities.
=> Bump Vulnerable Packages Version

.github/workflows/loc-update.yml
This pull request adds a new GitHub Actions workflow to automate the process of updating localization files when changes are made to the `loc` directory. 
* `.github/workflows/loc-update.yml`: Introduced a new workflow named "Localization Update" that triggers on pull requests targeting the `main` branch and involving changes in the `loc` directory. The workflow performs the following steps:
- Checks out the repository using `actions/checkout@v4`.
- Sets up Node.js version 18 with npm caching using `actions/setup-node@v4`.
- Runs the `translations-import` script to update localization files.
- Checks for changes in the repository and commits/pushes them back if any updates are detected.
=> Add localization update GitHub workflow

src/common/copilot/assets/scripts/copilot.js
Previous PR: https://github.com/microsoft/powerplatform-vscode/pull/1222
Updating the suppression reason
=> Update Suppression Justification Message

.github/workflows/loc-update.yml, CHANGELOG.md, gulpfile.mjs, src/common/copilot/assets/scripts/copilot.js
This pull request introduces a new GitHub Actions workflow for automating localization updates and updates the Power Platform Extension to use a newer pac CLI version. Additionally, it makes minor improvements to the `copilot.js` script by clarifying comments related to input sanitization.
**Automation and CI/CD improvements:**
* Added `.github/workflows/loc-update.yml` to automate localization file updates on pull requests affecting the `loc/**` directory. The workflow checks out the repo, installs dependencies, runs the translation import, and commits changes automatically.
**Dependency and version updates:**
* Updated pac CLI version from `1.45.3` to `1.46.1` in both `CHANGELOG.md` and `gulpfile.mjs` to ensure the extension uses the latest CLI features and fixes. …
=> [July Release] [PAC 1.46.1] Merge main to release

package-lock.json
Updating form-data to its latest version, which is more secure.
=> Update form-data version

CHANGELOG.md, gulpfile.mjs
Fix for the duplicate webpage issue included.
=> Update CHANGELOG for pac CLI 1.47.1 release

.github/workflows/PullRequest.yml, .vscode/tasks.json, CHANGELOG.md, gulpfile.mjs, localize/LocProject.json, package-lock.json, package.json, src/client/extension.ts, src/common/ecs-features/ecsFeatureGates.ts, src/common/intellisense/ServerApiAutocompleteRegistrar.ts, src/common/intellisense/ServerApiCompletionProvider.ts, src/common/intellisense/ServerApiTelemetryContext.ts, src/common/intellisense/ServerApiTelemetryEventNames.ts, src/common/intellisense/index.ts, src/common/test/integration/ServerApiAutocomplete.test.ts, src/common/test/integration/index.ts, src/common/test/runTest.ts, src/web/client/dal/remoteFetchProvider.ts, src/web/client/extension.ts, src/web/client/schema/constants.ts
This pull request introduces Server API autocomplete functionality for Power Pages JavaScript development in VS Code, including feature gating, telemetry support, and integration into the extension activation flow. It also updates the pac CLI version, adds new integration test support, and improves TypeScript build configuration.
**Server API Autocomplete & Telemetry Integration:**
* Added `ServerApiAutocompleteRegistrar`, telemetry context utilities, and event names to enable and track Server API IntelliSense features for JavaScript in Power Pages, including registration helpers and activation logic. [[1]](diffhunk://#diff-609cabbeb12eed65dadbb079303eb64c1d31e8b4d8570a4445392db40c3d69d9R1-R156) [[2]](diffhunk://#diff-6420bafbd963c08165f4c690387e2efde4aabe51aaa4055dc26e6cb397d15f52R1-R22) …
=> Pac 1.47.1 Update

.github/copilot-instructions.md, CHANGELOG.md
=> Update release branch

.github/workflows/loc-update.yml
Update localization pipeline node version
=> Update localization pipeline node version

.github/workflows/loc-update.yml
- 🔧 Added token configuration for checkout step
- 🔒 Ensured GITHUB_TOKEN is set for commit and push step
=> Fix token handling in localization update workflow

.github/instructions/memory-bank.instructions.md, memory-bank/activeContext.md, memory-bank/productContext.md, memory-bank/progress.md, memory-bank/projectbrief.md, memory-bank/systemPatterns.md, memory-bank/techContext.md
- 📝 Created initial Memory Bank structure and core files.
- 📄 Documented project overview, architecture, and workflows. 
- 🔧 Included detailed descriptions of features and user scenarios. 
- 📊 Established progress tracking and technical context.
=> Add comprehensive Memory Bank documentation

src/common/OneDSLoggerTelemetry/telemetryConstants.ts
Replace the GOV instrumentation key with the correct value.
=> Update GOV Instrumentation Key

gulpfile.mjs
Bump PAC to 1.49.3 
https://www.nuget.org/packages/Microsoft.PowerApps.CLI
=> Bump PAC to 1.49.3

gulpfile.mjs
Bump PAC to 1.49.4 
https://www.nuget.org/packages/Microsoft.PowerApps.CLI
=> Bump PAC to 1.49.4
